### PR TITLE
Connect-DbaInstance: Fix problems with DAC

### LINKED ISSUE #9253: [Copy-DbaCredential] Failed to decrypt credentials
### Verified issue does not already exist?

I have searched and found no existing issue

### What error did you receive?

Copy-DbaCredential -Source primary\sql1 -Destination secondary\sql1 -Name "Test" -verbose

VERBOSE: [10:20:58][Copy-DbaCredential] We will try to use a dedicated admin connection.
VERBOSE: [10:20:58][Connect-DbaInstance] String is passed in, will build server object from instance object and other parameters, do some checks and then return the server object
VERBOSE: [10:20:58][Connect-DbaInstance] authentication method is 'local integrated'
VERBOSE: [10:20:58][Copy-DbaCredential] Decrypting all Credential logins and passwords on ADMIN:primary\sql1
VERBOSE: [10:20:58][Get-DecryptedObject] Querying service master key
**WARNING: [10:20:58][Copy-DbaCredential] Failed to decrypt credentials on ADMIN:primary\sql1 | You cannot call a method on a null-valued expression.**

### Steps to Reproduce

```powershell
Copy-DbaCredential -Source primary\sql1 -Destination secondary\sql1 -Name "Test" -verbose
```


### Please confirm that you are running the most recent version of dbatools

2.0.4

### Other details or mentions

_No response_

### What PowerShell host was used when producing this error

Windows PowerShell ISE (powershell_ise.exe)

### PowerShell Host Version


Name                           Value                                                                                                                                                                                                                             
----                           -----                                                                                                                                                                                                                             
PSVersion                      5.1.20348.1850                                                                                                                                                                                                                    
PSEdition                      Desktop                                                                                                                                                                                                                           
PSCompatibleVersions           {1.0, 2.0, 3.0, 4.0...}                                                                                                                                                                                                           
BuildVersion                   10.0.20348.1850                                                                                                                                                                                                                   
CLRVersion                     4.0.30319.42000                                                                                                                                                                                                                   
WSManStackVersion              3.0                                                                                                                                                                                                                               
PSRemotingProtocolVersion      2.3                                                                                                                                                                                                                               
SerializationVersion           1.1.0.1                                                                                                                                                                                                                           




### SQL Server Edition and Build number

Microsoft SQL Server 2022 (RTM-CU7) (KB5028743) - 16.0.4065.3 (X64)   Jul 25 2023 18:03:43   Copyright (C) 2022 Microsoft Corporation  Enterprise Edition: Core-based Licensing (64-bit) on Windows Server 2022 Standard 10.0 <X64> (Build 20348: ) 

### .NET Framework Version

PSChildName                      Version       
-----------                      -------       
v2.0.50727                       2.0.50727.4927
v3.0                             3.0.30729.4926
Windows Communication Foundation 3.0.4506.4926 
Windows Presentation Foundation  3.0.6920.4902 
v3.5                             3.5.30729.4926
Client                           4.8.04161     
Full                             4.8.04161     
Client                           4.0.0.0

### PR DESCRIPTION
**Pull request by andreasjordan**
## Type of Change

 - [x] Bug fix (non-breaking change, fixes #9253 )
 - [ ] New feature (non-breaking change, adds functionality, fixes # )
 - [ ] Breaking change (affects multiple commands or functionality, fixes # )
 - [ ] Ran manual Pester test and has passed (`.\tests\manual.pester.ps1`)
 - [ ] Adding code coverage to existing functionality
 - [ ] Pester test is included
 - [ ] If new file reference added for test, has is been added to github.com/dataplat/appveyor-lab ?
 - [ ] Unit test is included
 - [ ] Documentation
 - [ ] Build system

### Purpose
We need to prevent the cache to be used for DAC.

We need to close new connections if we do not return them.

Because of test refactoring, the diff of the tests is a bit hard to read - sorry for that.

### CODE REVIEW

**Comment by andreasjordan** [comment]
@wsmelton - If you have time, please have a look at the tests. Maybe you have additional suggestions.

**Comment by potatoqualitee** [comment]
good call, and what a ton of work! thank you very much 🙇🏼

**Comment by potatoqualitee** [comment]
Do you have any concerns about the changes that were made, @andreasjordan ? For example, did you have to change the substance of any tests to for them to work?

**Comment by potatoqualitee** [comment]
excellent, thanks again! 💯

**Comment by 00-schaudhary** [comment]
Hi,

Is this change available in the latest update or is it still pending merge? If already available, I can update and test.

**Comment by andreasjordan** [comment]
Yes, it's included in the current version.

**Comment by 00-schaudhary** [comment]
@andreasjordan - I updated dbatools to 2.1.18. Everything seems to be working fine now. Thank you for fixing this!

**Comment by andreasjordan** [comment]
Thanks for the feedback.

**Pull request merged**
