### PR TITLE
New-DbaDbTable - Drop table if creation fails and change DefaultEx to DefaultExpression

### PR DESCRIPTION
**Pull request by andreasjordan**
## Type of Change

 - [ ] Bug fix (non-breaking change, fixes # )
 - [x] New feature (non-breaking change, adds functionality, fixes # )
 - [ ] Breaking change (effects multiple commands or functionality, fixes # )
 - [ ] Ran manual Pester test and has passed (`.\tests\manual.pester.ps1`)
 - [ ] Adding code coverage to existing functionality
 - [ ] Pester test is included
 - [ ] If new file reference added for test, has is been added to github.com/dataplat/appveyor-lab ?
 - [ ] Unit test is included
 - [ ] Documentation
 - [ ] Build system

### CODE REVIEW

**Comment by andreasjordan** [comment]
Don't know why the unrelated test fails.

**Comment by potatoqualitee** [comment]
Rerunning all incomplete

**Comment by potatoqualitee** [comment]
oh hey andreas, tests for new-dbadbtable are disabled on Appveyor

```
# do not run on appveyor
    "appveyor_disabled" = @(
```

found that by looking for what could possibly be impacting that other command that's failing

**Comment by potatoqualitee** [comment]
Seems it fails too often -- perhaps create a test on `gh-actions.ps1`

**Comment by potatoqualitee** [comment]
you can also remove that test from `pester.groups.ps1` to actually make it run, to see if tests actually pass

**Comment by andreasjordan** [comment]
Thanks for the hint - now it works, tests pass.
Is there anything else that should be included in this PR? What about "DefaultString"?

**Comment by potatoqualitee** [comment]
I like that too, if you wish

**Comment by drstonephd** [comment]
Wow, you folks are fast.  I like the DefaultExpression and DefaultString.  DBATools makes a DBAs life easier.  Thanks!

**Pull request merged**
