### PR TITLE
DacFX - Fix strong-name signing is not supported on this platform

### PR DESCRIPTION
**Pull request by potatoqualitee**
Fixes part of #8014 -- I still need to do the Windows DLLs.

### CODE REVIEW

**Comment by potatoqualitee** [comment]
need to test azure with these dlls too. they somehow interact

**Comment by potatoqualitee** [comment]
Integration tests pass ✅ Post PRs/reviews welcome. Seems not a lot of activity at this time so I'm rushing it a little along while I'm motivated.

I'll potentially submit a PR for the Windows full .net library. Right now, this takes care of Core. So there's a slight mismatch in sqlpackage(.exe) versions

**Comment by potatoqualitee** [comment]
Integration tests pass ✅ Post PRs/reviews welcome. Seems not a lot of activity at this time so I'm rushing it a little along while I'm motivated.

I'll potentially submit a PR for the Windows full .net library. Right now, this takes care of Core. So there's a slight mismatch in sqlpackage(.exe) versions

**Comment by techvslife** [comment]
@potatoqualitee Thanks, I confirm this all works now!

**Pull request merged**
