### PR TITLE
Test-DbaConnection - Fix for wrong data in failed connections

### LINKED ISSUE #9066: Test-DbaConnection returns properties of previous instance when connection fails in a loop
### Verified issue does not already exist?

I have searched and found no existing issue

### What error did you receive?

no error

when there is no connection to a sql instance, the properties 'authtype', 'authscheme' a.o. from the previous object are returned.

### Steps to Reproduce

```powershell
Test-DBAConnection -SqlInstance 'IDoNotExist'
  
Test-DBAConnection -SqlInstance 'SQLServer1','IDoNotExist'
```

### Please confirm that you are running the most recent version of dbatools

2.0.4

### Other details or mentions

_No response_

### What PowerShell host was used when producing this error

PowerShell Core (pwsh.exe)

### PowerShell Host Version

7.3.6

### SQL Server Edition and Build number

all

### .NET Framework Version

7.0.9

### PR DESCRIPTION
**Pull request by HarrisonLond**
## Please read -- recent changes to our repo
On November 10, 2022, [we removed some bloat from our repository (for the second and final time)](https://github.com/dataplat/dbatools/issues/8542). This change requires that all contributors reclone or refork their repo.

PRs from repos that have not been recently reforked or recloned will be closed and @potatoqualitee will cherry-pick your commits and open a new PR with your changes.

 - [ ] Please confirm you have the smaller repo (85MB .git directory vs 275MB or 110MB or 185MB .git directory)

## Type of Change

 - [X] Bug fix (non-breaking change, fixes #9066 )
 - [ ] New feature (non-breaking change, adds functionality, fixes # )
 - [ ] Breaking change (affects multiple commands or functionality, fixes # )
 - [ ] Ran manual Pester test and has passed (`.\tests\manual.pester.ps1`)
 - [ ] Adding code coverage to existing functionality
 - [ ] Pester test is included
 - [ ] If new file reference added for test, has is been added to github.com/dataplat/appveyor-lab ?
 - [ ] Unit test is included
 - [ ] Documentation
 - [ ] Build system

### CODE REVIEW

**Comment by andreasjordan** [comment]
Code looks good to me. But we don't use ";" at the end of the lines. I would suggest removing them.

**Comment by andreasjordan** [comment]
And welcome to dbatools and thanks for the pull request!

**Comment by HarrisonLond** [comment]
> Code looks good to me. But we don't use ";" at the end of the lines. I would suggest removing them.

Hi, Sorry i'm a little new to this, can I amend my request or would I need to repeat the process for a new pull request removing the semi colons?

**Comment by andreasjordan** [comment]
You can just add a new commit, that will update the pull request.

Or I can change the code for you.

**Comment by HarrisonLond** [comment]
> You can just add a new commit, that will update the pull request.
> 
> Or I can change the code for you.

Thanks, Have now done.

**Review by andreasjordan — APPROVED** [review]
Code looks good to me. Thanks for the pull request.

**Comment by andreasjordan** [comment]
Only test of New-DbaDbSnapshot failed, which is unrelated.

**Comment by potatoqualitee** [comment]
That snapshot has given us issues on and off. I'll disable it momentarily. Thank you both, so much, for your work 🙇🏼

**Pull request merged**
