### PR TITLE
New command: Test-DbaBackupEncrypted

### PR DESCRIPTION
**Pull request by potatoqualitee**
```powershell
Test-DbaBackupEncrypted -SqlInstance $script:instance2 -FilePath $backup.BackupPath

ComputerName        : sqlcs
InstanceName        : MSSQLSERVER
SqlInstance         : sqlcs
FilePath            : C:\temp\random-1545190794_202201160217.bak
BackupName          : 
Encrypted           : False
KeyAlgorithm        : 
EncryptorThumbprint : 
EncryptorType       : 
TDEThumbprint       :
Compressed          : False
```

and
```powershell
$output.BackupPath | Test-DbaBackupEncrypted -SqlInstance sqlcs

ComputerName        : sqlcs
InstanceName        : MSSQLSERVER
SqlInstance         : sqlcs
FilePath            : c:\temp\pubs1_202201160212.bak
BackupName          :
Encrypted           : True
KeyAlgorithm        : aes_192
EncryptorThumbprint : 168
EncryptorType       : CERTIFICATE
TDEThumbprint       :
Compressed          : True
```

and
```powershell
Test-DbaBackupEncrypted -SqlInstance macmini -FilePath /shared/nw2.bak


ComputerName        : macmini
InstanceName        : MSSQLSERVER
SqlInstance         : mssql1
FilePath            : /shared/nw2.bak
BackupName          : Northwind-Full Database Backup
Encrypted           : True
KeyAlgorithm        :
EncryptorThumbprint :
EncryptorType       :
TDEThumbprint       : 0xEF9CB9F92B8E812A7A11A34FEEA5049DF95D705B
Compressed          : True
```

### CODE REVIEW

**Comment by potatoqualitee** [comment]
lol, every single one of the commands says Encypted.

**Comment by potatoqualitee** [comment]
```
$params2 = @{
    SqlInstance             = "macmini"
    SqlCredential           = $cred
    MasterKeySecurePassword = $passwd
    BackupSecurePassword    = $passwd
    BackupPath              = "/shared"
    AllUserDatabases        = $true
}
Start-DbaDbEncryption @params2 -Confirm:$false


$params1 = @{
    Source = "macmini"
    SourceSqlCredential           = $cred
    Destination = "macmini:14334"
    DestinationSqlCredential           = $sacred
    EncryptionPassword = $passwd
    MasterKeyPassword = $passwd
    SharedPath              = "/shared"
}
#new command im working on
Copy-DbaDbCertificate @params1 -Confirm:$false -OutVariable results
```

**Review by ClaudioESSilva — APPROVED** [review]
🔥🔥🔥

**Comment by potatoqualitee** [comment]
Thanks bud! 🥳

**Pull request merged**
