### PR TITLE
Restore-DbaDatabase - Enable summing TotalSize if input is from CliXml exported file

### LINKED ISSUE #8778: Restore-DbaDatabase errors summing TotalSize if input is from CliXml exported file
### Verified issue does not already exist?

I have searched and found no existing issue

### What error did you receive?

Measure-Object : Input object "922.09 MB" is not numeric.
At C:\Users\viacoboni2\Documents\WindowsPowerShell\Modules\dbatools\1.1.134\allcommands.ps1:69857 char:153
+ ... th]::Round(($backup | Measure-Object -Property TotalSize -Sum).Sum /  ...
+                           ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : InvalidType: (922.09 MB:PSObject) [Measure-Object], PSInvalidOperationException
    + FullyQualifiedErrorId : NonNumericInputObject,Microsoft.PowerShell.Commands.MeasureObjectCommand

Measure-Object : Input object "44.76 MB" is not numeric.
At C:\Users\viacoboni2\Documents\WindowsPowerShell\Modules\dbatools\1.1.134\allcommands.ps1:69858 char:164
+ ... (($backup | Measure-Object -Property CompressedBackupSize -Sum).Sum / ...
+                 ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : InvalidType: (44.76 MB:PSObject) [Measure-Object], PSInvalidOperationException
    + FullyQualifiedErrorId : NonNumericInputObject,Microsoft.PowerShell.Commands.MeasureObjectCommand

Measure-Object : Input object "922.09 MB" is not numeric.
At C:\Users\viacoboni2\Documents\WindowsPowerShell\Modules\dbatools\1.1.134\allcommands.ps1:69863 char:149
+ ...  [dbasize](($backup | Measure-Object -Property TotalSize -Sum).Sum /  ...
+                           ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : InvalidType: (922.09 MB:PSObject) [Measure-Object], PSInvalidOperationException
    + FullyQualifiedErrorId : NonNumericInputObject,Microsoft.PowerShell.Commands.MeasureObjectCommand

Measure-Object : Input object "44.76 MB" is not numeric.
At C:\Users\viacoboni2\Documents\WindowsPowerShell\Modules\dbatools\1.1.134\allcommands.ps1:69864 char:160
+ ... (($backup | Measure-Object -Property CompressedBackupSize -Sum).Sum / ...
+                 ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : InvalidType: (44.76 MB:PSObject) [Measure-Object], PSInvalidOperationException
    + FullyQualifiedErrorId : NonNumericInputObject,Microsoft.PowerShell.Commands.MeasureObjectCommand

### Steps to Reproduce

```powershell
PS> Get-DbaDbBackupHistory -SqlInstance MySourceServer -Database MyDb -LastFull | Export-Clixml -Depth 5 -Path .\MyDb_LastFull.xml
PS> Get-DbaBackupInformation -Import -Path .\MyDb_LastFull.xml | Restore-DbaDatabase -SqlInstance MyDestServer -DatabaseName MyDb_test -TrustDbBackupHistory -ReplaceDbNameInFile
Measure-Object : Input object "922.09 MB" is not numeric.
At C:\Users\viacoboni2\Documents\WindowsPowerShell\Modules\dbatools\1.1.134\allcommands.ps1:69857 char:153
+ ... th]::Round(($backup | Measure-Object -Property TotalSize -Sum).Sum /  ...
+                           ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : InvalidType: (922.09 MB:PSObject) [Measure-Object], PSInvalidOperationException
    + FullyQualifiedErrorId : NonNumericInputObject,Microsoft.PowerShell.Commands.MeasureObjectCommand

Measure-Object : Input object "44.76 MB" is not numeric.
At C:\Users\viacoboni2\Documents\WindowsPowerShell\Modules\dbatools\1.1.134\allcommands.ps1:69858 char:164
+ ... (($backup | Measure-Object -Property CompressedBackupSize -Sum).Sum / ...
+                 ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : InvalidType: (44.76 MB:PSObject) [Measure-Object], PSInvalidOperationException
    + FullyQualifiedErrorId : NonNumericInputObject,Microsoft.PowerShell.Commands.MeasureObjectCommand

Measure-Object : Input object "922.09 MB" is not numeric.
At C:\Users\viacoboni2\Documents\WindowsPowerShell\Modules\dbatools\1.1.134\allcommands.ps1:69863 char:149
+ ...  [dbasize](($backup | Measure-Object -Property TotalSize -Sum).Sum /  ...
+                           ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : InvalidType: (922.09 MB:PSObject) [Measure-Object], PSInvalidOperationException
    + FullyQualifiedErrorId : NonNumericInputObject,Microsoft.PowerShell.Commands.MeasureObjectCommand

Measure-Object : Input object "44.76 MB" is not numeric.
At C:\Users\viacoboni2\Documents\WindowsPowerShell\Modules\dbatools\1.1.134\allcommands.ps1:69864 char:160
+ ... (($backup | Measure-Object -Property CompressedBackupSize -Sum).Sum / ...
+                 ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : InvalidType: (44.76 MB:PSObject) [Measure-Object], PSInvalidOperationException
    + FullyQualifiedErrorId : NonNumericInputObject,Microsoft.PowerShell.Commands.MeasureObjectCommand



ComputerName         : MyDestServer
InstanceName         : MSSQLSERVER
SqlInstance          : MyDestServer
BackupFile           : C:\SqlBackups\MySourceServer\MyDb\FULL\MySourceServer_MyDb_FULL_20230225_194437_1.bak,C:\SqlBackups\MySourceServer\MyDb\FULL\MySourceServer_MyDb
                       _FULL_20230225_194437_2.bak
BackupFilesCount     : 2
BackupSize           : 0 B
CompressedBackupSize : 0 B
Database             : MyDb_test
Owner                : MyOrg\VIACOBONI2
DatabaseRestoreTime  : 00:00:06
FileRestoreTime      : 00:00:05
NoRecovery           : False
RestoreComplete      : True
RestoredFile         : MyDb_test_Data.MDF,MyDb_test_Log.LDF
RestoredFilesCount   : 2
Script               : {RESTORE DATABASE [MyDb_test] FROM  DISK = N'C:\SqlBackups\MySourceServer\MyDb\FULL\MySourceServer_MyDb_FULL_20230225_194437_1.bak',  DISK =
                       N'C:\SqlBackups\MySourceServer\MyDb\FULL\MySourceServer_MyDb_FULL_20230225_194437_2.bak' WITH  FILE = 1,  MOVE N'MyDb_Data' TO
                       N'D:\Data\MyDb_test_Data.MDF',  MOVE N'MyDb_Log' TO N'F:\Logs\MyDb_test_Log.LDF',  NOUNLOAD,  STATS = 10}
RestoreDirectory     : D:\Data,F:\Logs
WithReplace          : False
```

### Please confirm that you are running the most recent version of dbatools

1.1.134

### Other details or mentions

I will be submitting a pull request to fix the issue.

```powershell
$bh = Get-DbaDbBackupHistory -SqlInstance MySourceServer -Database MyDb -LastFull  # Get History from MSDB
Get-DbaDbBackupHistory -SqlInstance MySourceServer -Database MyDb -LastFull | 
  Export-Clixml -Depth 5 -Path .\MyDb_LastFull.xml                                 # Export backup history to XML  
$bhi = Import-Clixml -Path .\BranchFileTransfer_LastFull.xml                       # Import history from XML
$bh | Measure-Object TotalSize -Sum                                                # Current code works for direct history
$bhi | Measure-Object TotalSize -Sum | select Sum                                  # But fails if from imported XML
Measure-Object : Input object "922.09 MB" is not numeric.
At line:1 char:8
+ $bhi | Measure-Object TotalSize -Sum | select Sum
+        ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : InvalidType: (922.09 MB:PSObject) [Measure-Object], PSInvalidOperationException
    + FullyQualifiedErrorId : NonNumericInputObject,Microsoft.PowerShell.Commands.MeasureObjectCommand

$bhi | Select-Object -ExpandProperty TotalSize | Measure-Object Megabyte -Sum     # Using -ExpandProperty on TotalSize fixes it
$bh  | Select-Object -ExpandProperty TotalSize | Measure-Object Megabyte -Sum     # Also works with direct history
```

### What PowerShell host was used when producing this error

Windows PowerShell (powershell.exe)

### PowerShell Host Version

Name                           Value                                                                                   
----                           -----                                                                                   
PSVersion                      5.1.17763.3770                                                                          
PSEdition                      Desktop                                                                                 
PSCompatibleVersions           {1.0, 2.0, 3.0, 4.0...}                                                                 
BuildVersion                   10.0.17763.3770                                                                         
CLRVersion                     4.0.30319.42000                                                                         
WSManStackVersion              3.0                                                                                     
PSRemotingProtocolVersion      2.3                                                                                     
SerializationVersion           1.1.0.1                                                                                 

### SQL Server Edition and Build number

Microsoft SQL Server 2019 (RTM-CU17) (KB5016394) - 15.0.4249.2 (X64)
                Jul 22 2022 12:11:33
                Copyright (C) 2019 Microsoft Corporation
                Developer Edition (64-bit) on Windows Server 2019 Standard 10.0 <X64> (Build 17763: ) (Hypervisor)

### .NET Framework Version

PSChildName Version
----------- -------
Client      4.8.03761
Full        4.8.03761
Client      4.0.0.0

### PR DESCRIPTION
**Pull request by potatoqualitee**
Fixes #8778

It can probably be fixed in 1.x with:

```
Set-DbatoolsConfig -FullName formatting.size.style -Value b
```

### CODE REVIEW

**Comment by potatoqualitee** [comment]
lol, super broke. fixing...

**Comment by potatoqualitee** [comment]
all tests pass 👍🏼

**Comment by sqlslinger** [comment]
Thanks @potatoqualitee!

**Comment by sqlslinger** [comment]
> Fixes #8778
> 
> It can probably be fixed in 1.x with:
> 
> ```
> Set-DbatoolsConfig -FullName formatting.size.style -Value b
> ```

I don't think that fixes in 1.x, see [here](https://github.com/dataplat/dbatools/issues/8778#issuecomment-1501926800).

**Pull request merged**
