### PR TITLE
Get-DbaCmObject - Improved CIM ErrorHandling

### PR DESCRIPTION
**Pull request by FriedrichWeinmann**
+ Centralized error resolution (Pure code cleanup & deduplication)
+ Added CIM/DCOM error handling for bad namespaces/class names

## Please read -- recent changes to our repo
On November 10, 2022, [we removed some bloat from our repository (for the second and final time)](https://github.com/dataplat/dbatools/issues/8542). This change requires that all contributors reclone or refork their repo.

PRs from repos that have not been recently reforked or recloned will be closed and @potatoqualitee will cherry-pick your commits and open a new PR with your changes.

 - [x] Please confirm you have the smaller repo (85MB .git directory vs 275MB or 110MB or 185MB .git directory)

## Type of Change

 - [x] Bug fix (non-breaking change, fixes # )
 - [ ] New feature (non-breaking change, adds functionality, fixes # )
 - [ ] Breaking change (affects multiple commands or functionality, fixes # )
 - [ ] Ran manual Pester test and has passed (`.\tests\manual.pester.ps1`)
 - [ ] Adding code coverage to existing functionality
 - [ ] Pester test is included
 - [ ] If new file reference added for test, has is been added to github.com/dataplat/appveyor-lab ?
 - [ ] Unit test is included
 - [ ] Documentation
 - [ ] Build system

### Purpose

When using CIM/DCOM (which automatically happens when executing against localhost), errors for bad namespace or class name - e.g. searching for SQL Service details on a machine that does not have the namespace - would incorrectly flag the machine as not reachable, due to .NET not correctly classifying the error record.

### Approach

+ Centralized the error resolution to simplify the code
+ Added manual HResult error mapping as a fallback

### Commands to test

The only modified command is `Get-DbaCmObject`.
To reproduce the error fixed, run the following two lines on the current gallery version.

```powershell
Get-DbaCmObject -Query 'SELECT * FROM Win32_Servize' -ComputerName $env:COMPUTERNAME
Get-DbaCmObject -Query 'SELECT * FROM Win32_Service' -ComputerName $env:COMPUTERNAME
```

Executing the same again in this fixed version will work just fine :)

### CODE REVIEW

**Comment by potatoqualitee** [comment]
heeyyyyy, good to see you! thank you for the PR 🙇🏼

**Comment by FriedrichWeinmann** [comment]
Aaaaand here's the second part on the library side, to expand into supporting `Invoke-CimMethod`, not just reading:

https://github.com/dataplat/dbatools.library/pull/5

**Comment by potatoqualitee** [comment]
Thank you @FriedrichWeinmann ! It will take me a moment to find my scritps to rebuild the library. Things changed drastically. I'll return to this asap.

**Comment by potatoqualitee** [comment]
thank you 🙇🏼

**Pull request merged**
