### PR TITLE
Sync-DbaLoginPassword - command to sync passwords based on hashed value

### LINKED ISSUE #1032: Sync-SqlLoginPermissions - Option to only update existing passwords without dropping anything
### Is this a *feature* OR *bug*:
Feature - Basically a useful feature would be to transmit the current passwords to the user accounts on a remote box for matching users.

### LINKED ISSUE #8980: Set-DbaLogin - processing all logins even if you only pass in one
### Verified issue does not already exist?

No, I did not search

### What error did you receive?

No error, look at the verbose output of this command. Even if you provide a list of Logins to `-Login` it is still pulling every login on the instance. 

Because of this section of code, not sure why it was done this way, but we should not be pulling every possible login, and then filtering it.

https://github.com/dataplat/dbatools/blob/0433f3260cc448b8ca932b8da4a4b777a656768a/public/Set-DbaLogin.ps1#L240-L250

### Steps to Reproduce

```powershell
Set-DbaLogin -SqlInstance SomeServer -Login SomeLogin1 -Verbose
```

### Please confirm that you are running the most recent version of dbatools

Development branch

### Other details or mentions

_No response_

### What PowerShell host was used when producing this error

PowerShell Core (pwsh.exe)

### PowerShell Host Version

N/A

### SQL Server Edition and Build number

N/A

### .NET Framework Version

N/A

### PR DESCRIPTION
**Pull request by wsmelton**
Includes bumping the version of PSSA, so some commands not being caught before with formatting issues are included in this PR.

 - [x] Please confirm you have the smaller repo (85MB .git directory vs 275MB or 110MB or 185MB .git directory)

## Type of Change

 - [x] Bug fix (non-breaking change, fixes #8980 )
 - [x] New feature (non-breaking change, adds functionality, fixes #1032 )
 - [ ] Breaking change (affects multiple commands or functionality, fixes # )
 - [ ] Ran manual Pester test and has passed (`.\tests\manual.pester.ps1`)
 - [ ] Adding code coverage to existing functionality
 - [x] Pester test is included
 - [ ] If new file reference added for test, has is been added to github.com/dataplat/appveyor-lab ?
 - [x] Unit test is included
 - [x] Documentation
 - [ ] Build system

### Purpose
Adding functionality to support syncing passwords between instances using a hashed password value.

### Approach
Internal function added `Get-LoginPasswordHash` that uses T-SQL from Microsoft in the `sp_help_revlogin` to grab the hashed password value.

A number of updates to `Set-DbaLogin` to improve performance but also a new parameter, `-PasswordHash`, that allows it to handle setting the password by hash. It belongs in that command, and makes it where it can be used outside of the sync process if user desires.

This provides support for adding password sync to `Sync-DbaAvailabiltyGroup` now if anyone wishes.

### Commands to test
Test included

### Screenshots
image

image

### Learning

https://learn.microsoft.com/en-us/troubleshoot/sql/database-engine/security/transfer-logins-passwords-between-instances

### CODE REVIEW

**Comment by andreasjordan** [comment]
In case you have not seen it: AppVeyor says: Get-LoginPasswordHash.ps1 is not compliant with the OTBS formatting style

**Comment by potatoqualitee** [comment]
if its 100% failure every time, that usually does point to something. could some sort of use of "localhost" be an issue?

**Comment by wsmelton** [comment]
Why would splatting affect piping?

**Comment by wsmelton** [comment]
Yeah, what I figured. I removed my changes to the command and it still fails just like the snapshot command (that isn't touched in this PR).

**Comment by potatoqualitee** [comment]
k, rerunning just the fialed commands! I got a new code signing cert and will be margining singing this today.

**Comment by potatoqualitee** [comment]
aw nooo, there are conflicts 😭 i will hae to return to this one later but i do very much want the changes in there

**Comment by potatoqualitee** [comment]
lol this is getting worse, ill fix it when i have a chunk of time <3

**Comment by wsmelton** [comment]
The fault is our testing so all the changes in this PR are related to the PR context where I attempt to have the tests pass for the branch.

**Comment by potatoqualitee** [comment]
hey @wsmelton -- i got most things fixed except this one

```
Describe : Set-DbaDbOwner Integration Tests
Context  : Sets multiple database owners
Name     : It Sets the database owner on multiple databases
Result   : Failed
Message  : Expected 1, but got $null.
```

Any idea whats up?

**Comment by wsmelton** [comment]
Yeah that's the one that won't run correctly in Appeyor. That test runs fine locally.

**Comment by wsmelton** [comment]
I'm trying to figure out where I can get a lab spun up and will start working on this one again...

**Comment by potatoqualitee** [comment]
@claude can you review this PR, understand the original issue, and ultimately why the code is failing.

**Comment by potatoqualitee** [comment]
@claude once you figure it out, please create a new PR in a new Branch bc this one is too old

**Pull request closed without merging**
