### PR TITLE
Set-DbatoolsInsecureConnection - Use 'Optional' instead of false, and fix casing on PassThru parameter

### PR DESCRIPTION
**Pull request by awickham10**
## Please read -- recent changes to our repo
On November 10, 2022, [we removed some bloat from our repository (for the second and final time)](https://github.com/dataplat/dbatools/issues/8542). This change requires that all contributors reclone or refork their repo.

PRs from repos that have not been recently reforked or recloned will be closed and @potatoqualitee will cherry-pick your commits and open a new PR with your changes.

 - [x] Please confirm you have the smaller repo (85MB .git directory vs 275MB or 110MB or 185MB .git directory)

## Type of Change

 - [x] Bug fix (non-breaking change, fixes # )
 - [ ] New feature (non-breaking change, adds functionality, fixes # )
 - [ ] Breaking change (affects multiple commands or functionality, fixes # )
 - [ ] Ran manual Pester test and has passed (`.\tests\manual.pester.ps1`)
 - [ ] Adding code coverage to existing functionality
 - [x] Pester test is included
 - [ ] If new file reference added for test, has is been added to github.com/dataplat/appveyor-lab ?
 - [x] Unit test is included
 - [ ] Documentation
 - [ ] Build system

### Purpose

`Set-DbatoolsInsecureConnection` uses false instead of optional for the encrypt setting. This PR updates that to use optional.

### Approach

Updated cmdlet to pass `'Optional'` for the value instead of `$false`.

I also updated the casing on the PassThru parameter to be consistent with the `Set-DbatoolsConfig` cmdlet.

### Commands to test

`Set-DbatoolsInsecureConnection`

### CODE REVIEW

**Comment by awickham10** [comment]
Not really sure what this failure is about...

```
Exception calling "LeaveTestGroup" with "2" argument(s): "TestGroups stack corrupted:  Expected name/hint of 'C:\github\dbatools\tests\Get-DbaEstimatedCompletionTime.Tests.ps1','Script'.  Found 'Gets Query Estimated Completion', 
'Context'."
At C:\Program Files\WindowsPowerShell\Modules\Pester\4.4.2\Pester.psm1:880 char:21
+ ...                    $pester.LeaveTestGroup($testScript.Path, 'Script')
+                        ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : NotSpecified: (:) [], MethodInvocationException
    + FullyQualifiedErrorId : ScriptMethodRuntimeException
```

**Comment by wsmelton** [comment]
Is there an issue report showing why this is required or that it doesn't work as-is?

**Comment by awickham10** [comment]
Thanks. I originally thought true/false weren't working, now after really testing it I can't confirm it wasn't working. I've found various examples of this being set, some use true/false and some use mandatory/optional/strict.

Which is the preferred route? It seems like dbatools itself prefers mandatory/optional/strict (examples [here](https://github.com/dataplat/dbatools/blob/0d834691269b7484c580540366aee323ee019adb/.github/workflows/prerelease.yml#L29), [here](https://github.com/dataplat/dbatools/blob/0d834691269b7484c580540366aee323ee019adb/.github/workflows/integration-tests.yml#L30), [here](https://github.com/dataplat/dbatools/blob/0d834691269b7484c580540366aee323ee019adb/tests/appveyor.prep.ps1#L56), [here](https://github.com/dataplat/dbatools/blob/0d834691269b7484c580540366aee323ee019adb/public/New-DbaConnectionString.ps1#L53))

If not something we are worried about, I can close this out.

**Comment by wsmelton** [comment]
The Optional, by [documentation is actually wrong](https://learn.microsoft.com/en-us/dotnet/api/microsoft.sqlserver.management.common.sqlconnectioninfo.encryptconnection?view=sql-smo-160#microsoft-sqlserver-management-common-sqlconnectioninfo-encryptconnection) and not a valid value. This is more for discussion in an issue but as it stands not something we need to change for this set command.

**Comment by potatoqualitee** [comment]
Pretty sure Microsoft keeps changing this which is why there's confusion. Also sometimes it works and other times it doesn't. I'm as confused as you, @awickham10

**Comment by potatoqualitee** [comment]
Like check it out, @wsmelton linked docs that said true/false but then we got this, which is likely what i went by once or twice

https://learn.microsoft.com/en-us/dotnet/api/microsoft.data.sqlclient.sqlconnectionencryptoption

Sooo microsoft.sqlserver.management.common.sqlconnectioninfo.encryptconnection = true/false
https://learn.microsoft.com/en-us/dotnet/api/microsoft.sqlserver.management.common.sqlconnectioninfo.encryptconnection

microsoft.data.sqlclient.sqlconnectionencryptoption = optional, mandatory, strict 🤷🏼 
https://learn.microsoft.com/en-us/dotnet/api/microsoft.data.sqlclient.sqlconnectionencryptoption

Not sure what to do with this info

**Pull request closed without merging**
