### PR TITLE
Make Get-DbaPrivilege more efficient

### PR DESCRIPTION
**Pull request by mrahman-DBA**
Perform both the data extract and clean-up of the security policy file in just one trip to the remote computer(s). The extract is saved into the object `$secPol`, and further processing is made from only this object, which saves having to reach out to the remote computer(s) multiple times.

## Type of Change

 - [ ] Bug fix (non-breaking change, fixes # )
 - [ ] New feature (non-breaking change, adds functionality, fixes # )
 - [ ] Breaking change (affects multiple commands or functionality, fixes # )
 - [ ] Ran manual Pester test and has passed (`.\tests\manual.pester.ps1`)
 - [x] Adding code coverage to existing functionality
 - [ ] Pester test is included
 - [ ] If new file reference added for test, has is been added to github.com/dataplat/appveyor-lab ?
 - [ ] Unit test is included
 - [ ] Documentation
 - [ ] Build system

### Purpose
Make code more efficient

### Approach
The cmdlet was making multiple trips to the computer(s) to get data for each of the security policies. The code has been updated so that only one trip is made to the remote computer(s) and the data is saved into the `$secPol` object. Then further processing is made from only this object, which saves multiple trips to the remote computer(s)

### CODE REVIEW

**Comment by andreasjordan** [comment]
I like the idea of this pull request. I hope to find some time to do a review and test that in my lab.

**Comment by andreasjordan** [comment]
Our tests show:

Describe : dbatools style
Context  : formatting
Name     : It Get-DbaPrivilege.ps1 is not compliant with the OTBS formatting style. Please run Invoke-DbatoolsFormatter against the failing file and commit the changes.
Result   : Failed
Message  : Expected 0, but got 1.

Please have a look at the format of your changes.

**Comment by niphlod** [comment]
yeah it now checks out fine

**Comment by potatoqualitee** [comment]
Nice changes, thank you very much  🤩

**Pull request merged**
