### PR TITLE
ConvertTo-DbaDataTable handle Dataplat.Dbatools.Utility.DbaDateTime as an array

### LINKED ISSUE #9337: test-dbalastbackup  dates of backup files outputs Dataplat.Dbatools.Utility.DbaDateTime[]
### Verified issue does not already exist?

I have searched and found no existing issue

### What error did you receive?

I do weekly backup restore tests using test-dbalastbackup  and write the data using write-dbadbtabledata to a DB    Last week I updated DBATOOLS to 2.1.14 on April 12th.  My restore tests last week failed, and a test showed it was something changed and I had it make a new table.  Well this weekend my report ran and I saw what apparently changed.   The backup file dates now shows this in the table the scripts made / loaded.   Dataplat.Dbatools.Utility.DbaDateTime[]   Instead of the list of file dates.   I do also ignore log backups, and do just the full/diff files.

### Steps to Reproduce

```powershell
# provide your command(s) executed pertaining to dbatools
# please include variable values (redacted or fake if needed) for reference
```
Test-DbaLastBackup -SqlInstance Server1 -Destination DWSQL -IgnoreLogBackup |Write-DbaDbTableData -SqlInstance DWSQL -Database Backups -Table Testdata

### Please confirm that you are running the most recent version of dbatools

2.1.14

### Other details or mentions

_No response_

### What PowerShell host was used when producing this error

Windows PowerShell (powershell.exe)

### PowerShell Host Version

Name                           Value                                                                                                                 
----                           -----                                                                                                                 
PSVersion                      5.1.14393.6343                                                                                                        
PSEdition                      Desktop                                                                                                               
PSCompatibleVersions           {1.0, 2.0, 3.0, 4.0...}                                                                                               
BuildVersion                   10.0.14393.6343                                                                                                       
CLRVersion                     4.0.30319.42000                                                                                                       
WSManStackVersion              3.0                                                                                                                   
PSRemotingProtocolVersion      2.3                                                                                                                   
SerializationVersion           1.1.0.1                                                                                                               

### SQL Server Edition and Build number

Microsoft SQL Server 2022 (RTM-CU12) (KB5033663) - 16.0.4115.5 (X64)   Mar  4 2024 08:56:10   Copyright (C) 2022 Microsoft Corporation  Express Edition (64-bit) on Windows Server 2022 Standard 10.0 <X64> (Build 20348: ) (Hypervisor) 
Microsoft SQL Server 2022 (RTM-CU12) (KB5033663) - 16.0.4115.5 (X64)   Mar  4 2024 08:56:10   Copyright (C) 2022 Microsoft Corporation  Express Edition (64-bit) on Windows Server 2022 Standard 10.0 <X64> (Build 20348: ) (Hypervisor) 
Microsoft SQL Server 2022 (RTM-CU12) (KB5033663) - 16.0.4115.5 (X64)   Mar  4 2024 08:56:10   Copyright (C) 2022 Microsoft Corporation  Express Edition (64-bit) on Windows Server 2022 Standard 10.0 <X64> (Build 20348: ) (Hypervisor) 
Microsoft SQL Server 2019 (RTM-CU23) (KB5030333) - 15.0.4335.1 (X64)   Sep 21 2023 17:28:44   Copyright (C) 2019 Microsoft Corporation  Developer Edition (64-bit) on Windows Server 2019 Standard 10.0 <X64> (Build 17763: ) (Hypervisor) 
Microsoft SQL Server 2019 (RTM-CU18) (KB5017593) - 15.0.4261.1 (X64)   Sep 12 2022 15:07:06   Copyright (C) 2019 Microsoft Corporation  Express Edition (64-bit) on Windows Server 2019 Standard 10.0 <X64> (Build 17763: ) (Hypervisor) 
Microsoft SQL Server 2022 (RTM) - 16.0.1000.6 (X64)   Oct  8 2022 05:58:25   Copyright (C) 2022 Microsoft Corporation  Express Edition (64-bit) on Windows Server 2022 Standard 10.0 <X64> (Build 20348: ) (Hypervisor) 
Microsoft SQL Server 2019 (RTM-CU26) (KB5035123) - 15.0.4365.2 (X64)   Mar 29 2024 23:02:47   Copyright (C) 2019 Microsoft Corporation  Enterprise Edition: Core-based Licensing (64-bit) on Windows Server 2016 Standard 10.0 <X64> (Build 14393: ) (Hypervisor) 
Microsoft SQL Server 2022 (RTM) - 16.0.1000.6 (X64)   Oct  8 2022 05:58:25   Copyright (C) 2022 Microsoft Corporation  Developer Edition (64-bit) on Windows Server 2022 Standard 10.0 <X64> (Build 20348: ) (Hypervisor) 
Microsoft SQL Server 2022 (RTM) - 16.0.1000.6 (X64)   Oct  8 2022 05:58:25   Copyright (C) 2022 Microsoft Corporation  Express Edition (64-bit) on Windows Server 2022 Standard 10.0 <X64> (Build 20348: ) (Hypervisor) 
Microsoft SQL Server 2019 (RTM-CU26) (KB5035123) - 15.0.4365.2 (X64)   Mar 29 2024 23:02:47   Copyright (C) 2019 Microsoft Corporation  Enterprise Edition: Core-based Licensing (64-bit) on Windows Server 2019 Standard 10.0 <X64> (Build 17763: ) (Hypervisor) 
Microsoft SQL Server 2019 (RTM-CU26) (KB5035123) - 15.0.4365.2 (X64)   Mar 29 2024 23:02:47   Copyright (C) 2019 Microsoft Corporation  Enterprise Edition: Core-based Licensing (64-bit) on Windows Server 2016 Standard 10.0 <X64> (Build 14393: ) (Hypervisor) 
Microsoft SQL Server 2022 (RTM-CU12-GDR) (KB5036343) - 16.0.4120.1 (X64)   Mar 18 2024 12:02:14   Copyright (C) 2022 Microsoft Corporation  Developer Edition (64-bit) on Windows Server 2022 Standard 10.0 <X64> (Build 20348: ) (Hypervisor) 
Microsoft SQL Server 2022 (RTM) - 16.0.1000.6 (X64)   Oct  8 2022 05:58:25   Copyright (C) 2022 Microsoft Corporation  Developer Edition (64-bit) on Windows Server 2022 Standard 10.0 <X64> (Build 20348: ) (Hypervisor) 
Microsoft SQL Server 2016 (SP2) (KB4052908) - 13.0.5026.0 (X64)   Mar 18 2018 09:11:49   Copyright (c) Microsoft Corporation  Standard Edition (64-bit) on Windows Server 2019 Standard 10.0 <X64> (Build 17763: ) (Hypervisor) 
Microsoft SQL Server 2019 (RTM-CU15) (KB5008996) - 15.0.4198.2 (X64)   Jan 12 2022 22:30:08   Copyright (C) 2019 Microsoft Corporation  Standard Edition (64-bit) on Windows Server 2019 Standard 10.0 <X64> (Build 17763: ) (Hypervisor) 
Microsoft SQL Server 2019 (RTM-CU26) (KB5035123) - 15.0.4365.2 (X64)   Mar 29 2024 23:02:47   Copyright (C) 2019 Microsoft Corporation  Enterprise Edition: Core-based Licensing (64-bit) on Windows Server 2016 Standard 10.0 <X64> (Build 14393: ) (Hypervisor) 
Microsoft SQL Server 2019 (RTM) - 15.0.2000.5 (X64)   Sep 24 2019 13:48:23   Copyright (C) 2019 Microsoft Corporation  Express Edition (64-bit) on Windows Server 2019 Standard 10.0 <X64> (Build 17763: ) (Hypervisor) 
Microsoft SQL Server 2019 (RTM-CU15) (KB5008996) - 15.0.4198.2 (X64)   Jan 12 2022 22:30:08   Copyright (C) 2019 Microsoft Corporation  Standard Edition (64-bit) on Windows Server 2019 Standard 10.0 <X64> (Build 17763: ) (Hypervisor) 
Microsoft SQL Server 2019 (RTM-GDR) (KB5014356) - 15.0.2095.3 (X64)   Apr 29 2022 18:00:13   Copyright (C) 2019 Microsoft Corporation  Express Edition (64-bit) on Windows Server 2019 Standard 10.0 <X64> (Build 17763: ) (Hypervisor) 
Microsoft SQL Server 2019 (RTM-CU26) (KB5035123) - 15.0.4365.2 (X64)   Mar 29 2024 23:02:47   Copyright (C) 2019 Microsoft Corporation  Enterprise Edition: Core-based Licensing (64-bit) on Windows Server 2016 Standard 10.0 <X64> (Build 14393: ) (Hypervisor) 
Microsoft SQL Server 2016 (SP3) (KB5003279) - 13.0.6300.2 (X64)   Aug  7 2021 01:20:37   Copyright (c) Microsoft Corporation  Enterprise Edition: Core-based Licensing (64-bit) on Windows Server 2016 Standard 10.0 <X64> (Build 14393: ) (Hypervisor) 
Microsoft SQL Server 2019 (RTM-CU26) (KB5035123) - 15.0.4365.2 (X64)   Mar 29 2024 23:02:47   Copyright (C) 2019 Microsoft Corporation  Enterprise Edition: Core-based Licensing (64-bit) on Windows Server 2016 Standard 10.0 <X64> (Build 14393: ) (Hypervisor) 
Microsoft SQL Server 2019 (RTM-CU24) (KB5031908) - 15.0.4345.5 (X64)   Dec  4 2023 14:44:16   Copyright (C) 2019 Microsoft Corporation  Standard Edition (64-bit) on Windows Server 2019 Standard 10.0 <X64> (Build 17763: ) (Hypervisor) 
Microsoft SQL Server 2019 (RTM-CU26) (KB5035123) - 15.0.4365.2 (X64)   Mar 29 2024 23:02:47   Copyright (C) 2019 Microsoft Corporation  Enterprise Edition: Core-based Licensing (64-bit) on Windows Server 2019 Standard 10.0 <X64> (Build 17763: ) (Hypervisor) 
Microsoft SQL Server 2019 (RTM-CU26) (KB5035123) - 15.0.4365.2 (X64)   Mar 29 2024 23:02:47   Copyright (C) 2019 Microsoft Corporation  Enterprise Edition: Core-based Licensing (64-bit) on Windows Server 2019 Standard 10.0 <X64> (Build 17763: ) (Hypervisor) 
Microsoft SQL Server 2016 (SP3) (KB5003279) - 13.0.6300.2 (X64)   Aug  7 2021 01:20:37   Copyright (c) Microsoft Corporation  Standard Edition (64-bit) on Windows Server 2012 R2 Datacenter 6.3 <X64> (Build 9600: ) (Hypervisor) 
Microsoft SQL Server 2016 (SP3) (KB5003279) - 13.0.6300.2 (X64)   Aug  7 2021 01:20:37   Copyright (c) Microsoft Corporation  Standard Edition (64-bit) on Windows Server 2012 R2 Datacenter 6.3 <X64> (Build 9600: ) (Hypervisor) 

### .NET Framework Version

.NET Framework 4.7.4051.0

### PR DESCRIPTION
**Pull request by jpomfret**
## Type of Change

 - [X] Bug fix (non-breaking change, fixes #9337
 - [ ] New feature (non-breaking change, adds functionality, fixes # )
 - [ ] Breaking change (affects multiple commands or functionality, fixes # )
 - [ ] Ran manual Pester test and has passed (`.\tests\manual.pester.ps1`)
 - [ ] Adding code coverage to existing functionality
 - [ ] Pester test is included
 - [ ] If new file reference added for test, has is been added to github.com/dataplat/appveyor-lab ?
 - [ ] Unit test is included
 - [ ] Documentation
 - [ ] Build system

### Commands to test
```
Import-Module ./dbatools.psd1 -force
$cred = Get-Credential sqladmin
$inst = Connect-DbaInstance -SqlInstance localhost -SqlCredential $cred
$Results = Test-DbaLastBackup -SqlInstance $inst -Destination $inst -EnableException 
$test = ConvertTo-DbaDataTable -InputObject $Results
```

### CODE REVIEW

**Comment by wsmelton** [comment]
Fascinated how this test is passing because this test fails as I expect it to on my local machine
image

```pwsh
$innedobj = New-Object -TypeName psobject -Property @{
        Mission = 'Keep Hank alive'
    }

    Add-Member -Force -InputObject $obj -MemberType NoteProperty -Name myobject -Value $innedobj
```
The above sets `myObject` to a value (note that name should be camelCasing 😜) so this test is either false or we shouldn't be setting it to a value at all and just creating the property?

**Comment by wsmelton** [comment]
Just a few notes on this test as a whole, not something you must change unless you just want to include it in this PR...

- checking if a column name is on the object should use `-Contains` in Pester
  
image

- If you want to check if a given property is of a particular type use `-BeOfType`
image

- Checking for type also applies when you reference the nested object itself, `-BeOfType` can be used here

image

All of this just makes the test a bit easier to read.

**Comment by jpomfret** [comment]
> Fascinated how this test is passing because this test fails as I expect it to on my local machine

Ok I wondered how this was working because it wasn't working for me locally either - I've changed this to make sense (in my mind) and also updated the null one

**Comment by potatoqualitee** [comment]
oh sweet, we ready? thank you so much! i cant publish till i get home bc of the hardware key but happy to prep with a merge.

**Comment by potatoqualitee** [comment]
re-read and indeed. thanks again 🙇🏼

**Comment by potatoqualitee** [comment]
I skipped it in dev since its causing all of our branches to fail

**Comment by jpomfret** [comment]
Hey @potatoqualitee - I'm in Lisbon to see Taylor swift tonight 😂 but I'll take a look at this! It did pass locally and on the branch before merge 🤔

**Comment by potatoqualitee** [comment]
HEYYY enjoy taylor swift!!! we can look at this later 😊

**Comment by jpomfret** [comment]
@potatoqualitee 

I created a new branch off develoment and removed the `-skip` the tests ran fine 🤔 - also testing locally and it runs fine too.

https://github.com/dataplat/dbatools/tree/testingtests

https://ci.appveyor.com/project/dataplat/dbatools/builds/49936347
image

Is it worth uncommenting in development and seeing what happens? If not we can maybe troubleshoot and fix forward?

Honestly it's kind of a weird test anyway - we already test string values get converted ok - so I'm not sure what this is adding.
```PowerShell
    Context "Property: myObject" {
        It 'Has a column called "myObject"' {
            $result.Columns.ColumnName | Should -Contain 'myObject'
        }
        It 'Has a [string] data type on the column "myObject"' {
            $result.myObject | Should -BeOfType [System.String]
        }
    }
```

**Comment by potatoqualitee** [comment]
@jpomfret beautiful! and pfewf. So no change needed to the command, eh? Please do feel free to create a PR and I'll merge with the next batch.

**Comment by jpomfret** [comment]
so @potatoqualitee  ... when I went to PR the test was still skipped 🤦 

let me try this again - please hold 😂😂

**Comment by jpomfret** [comment]
This is so interesting - this test works completely different in appveyor vs locally

@wsmelton - remember this test - neither of us knew how it was passing in appveyor - I changed it to what was passing locally - and now it's failing in appveyor 😖 
https://github.com/dataplat/dbatools/pull/9361#issuecomment-2120920735

image

Shall I remove this test? or change it back to testing for null?

**Comment by niphlod** [comment]
lemme test "on my rig" and get back.

**Comment by potatoqualitee** [comment]
lol thanks niph, i had no idea how to make it pass

**Comment by niphlod** [comment]
yeah. beware that we have another problem, *I don't know why* "scenario 2008R2, part=1/2" for 2 weeks roughly is sooo borked that it fails badly an the "thingy" that reports back if something fails doesn't know what to read. It seems a pester 5 dependency has slipped in. 

https://ci.appveyor.com/project/dataplat/dbatools/builds/49958879/job/0386qjwfw6ofci83 , in particular https://ci.appveyor.com/project/dataplat/dbatools/builds/49958879/job/0386qjwfw6ofci83/tests and 
image

I don't know how to fix it but we may try to alter appveyor.yml on development to let it clear and re-cache dependencies, as most of them are linked to the content of [appveyor.yml itself](https://github.com/dataplat/dbatools/blob/development/appveyor.yml#L13) .

**Comment by niphlod** [comment]
tried my best, AND added some debug prints to uncover the "problem" , see https://ci.appveyor.com/project/dataplat/dbatools/build/job/68qbb1hlj9p98v9w

specifically, I *think* there might be some "strange happenings" around the fact that:
- ConvertTo-DbaDataTable returns `, $datatable`
- in .NET, a System.Data.DataTable, to access the value of a column named "col1" you need to do `dt.Rows[0]['col1']`
- PS *may* "reduce" the `, $datatable`, in the test case `$result` to the first occurrence
- tried various accessors, the result doesn't change
- if you try to "dump" via Json, the original object has the proper values, but trying to "dump" the column via Json ends up in a DBNull, indeed
- dumping the datatable via Json shows 
```
"Columns":  [
                                  "inlining2",
                                  "true",
                                  "char",
                                  "inlining",
                                  "dbadatetimeArray",
                                  "null",
                                  "guid",
                                  "dbadatetime",
                                  "UInt",
                                  "string",
                                  "timespan",
                                  "datetime",
                                  "false",
                                  "myObject"
                              ]
...

"ItemArray":  [
                      "System.Collections.Hashtable",
                      true,
                      "T",
                      null,
                      "2024-05-19 05:52:00.000, 2024-05-19 06:52:00.000",
                      null,
                      "32ccd4c4-282a-4c0d-997c-7b5deb97f9e0",
                      "2024-05-19 05:52:00.000",
                      [123](https://ci.appveyor.com/project/dataplat/dbatools/build/job/68qbb1hlj9p98v9w#L123)456,
                      "it\u0027s a boy.",
                      15724800000,
                      "\/Date(1477806720000)\/",
                      false,
                      null
                  ]
```

That being said, bumping appveyor.yml did fix the weird issue of a rogue pester 5 in the cache, and I modified:
- something around manual.pester.ps1 to be more precise 
- appveyor.pester.ps1 now dumps in the log what specific version of pester the test is run with

**Comment by jpomfret** [comment]
Thanks @niphlod for trying - so what do we think for this test, are we thinking it's not really testing what we want? Shall I remove that piece? 🤔

**Comment by niphlod** [comment]
pragmatically ..... something is going awry so if it's the one test causing problems (and, btw, it *seems* unrelated to serializing succesfully dbadatetime[]) so you may choose to just forget about it.
ideally this shows that at least with the combo of software/os/etc on appveyor, it appears that noteproperties are not succesfully serialized as they are "on our rigs".

**Comment by jpomfret** [comment]
Hmm @niphlod - can you check this failure for me? On the firstRow stuff you added in:
https://ci.appveyor.com/project/dataplat/dbatools/builds/49972082/job/rw3n9xlu79jedh3j

**Comment by niphlod** [comment]
sure @jpomfret , lemme revert all the "debug" prints, it was just to illustrate that the test fail(ed) because, indeed, that property was null in the first place.

**Comment by niphlod** [comment]
done, it *should* pass now (and not spit a blob of magenta lines).

**Comment by jpomfret** [comment]
Thank you 👏

**Comment by niphlod** [comment]
I stand corrected, https://github.com/dataplat/dbatools/pull/9384 has everything in.

**Pull request merged**
