### PR TITLE
Get-DbaKbUpdate - Fix for new URL style in microsoft catalog

### LINKED ISSUE #8275: Get-DbaKbUpdate not working
### Verified issue does not already exist?

Yes

### What error did you receive?

```
VERBOSE: GET http://www.catalog.update.microsoft.com/Search.aspx?q=KB4577194 with 0-byte payload
VERBOSE: received 45150-byte response of content type text/html; charset=utf-8
VERBOSE: [10:20:15][Get-DbaKbUpdate] 1b006ac2-a397-420b-b4d9-d6b13f053a52
VERBOSE: [10:20:15][Get-DbaKbUpdate] Downloading information for 1b006ac2-a397-420b-b4d9-d6b13f053a52
VERBOSE: POST https://www.catalog.update.microsoft.com/DownloadDialog.aspx with -1-byte payload
VERBOSE: received 37320-byte response of content type text/html; charset=utf-8
VERBOSE: GET
https://www.catalog.update.microsoft.com/ScopedViewInline.aspx?updateid=1b006ac2-a397-420b-b4d9-d6b13f053a52 with
0-byte payload
VERBOSE: received 27804-byte response of content type text/html; charset=utf-8
WARNING: [10:20:18][Get-DbaKbUpdate] Failure | You cannot call a method on a null-valued expression.
```

### Steps to Reproduce

try `Get-DbaKbUpdate -Name KB4577194 -Verbose` with latest dbatools, currently 1.1.85.

### Are you running the latest release?

Yes

### Other details or mentions

_No response_

### What PowerShell host was used when producing this error

Windows PowerShell (powershell.exe)

### PowerShell Host Version

Name                           Value                                                                                   
----                           -----                                                                                   
PSVersion                      5.1.19041.1320                                                                          
PSEdition                      Desktop                                                                                 
PSCompatibleVersions           {1.0, 2.0, 3.0, 4.0...}                                                                 
BuildVersion                   10.0.19041.1320                                                                         
CLRVersion                     4.0.30319.42000                                                                         
WSManStackVersion              3.0                                                                                     
PSRemotingProtocolVersion      2.3                                                                                     
SerializationVersion           1.1.0.1                                                                                 

### SQL Server Edition and Build number

Microsoft SQL Server 2019 (RTM-GDR) (KB4583458) - 15.0.2080.9 (X64)   Nov  6 2020 16:50:01   Copyright (C) 2019 Microsoft Corporation  Enterprise Edition (64-bit) on Windows 10 Enterprise 10.0 <X64> (Build 19043: ) 

### .NET Framework Version

```
PSChildName                      Version        Release
-----------                      -------        -------
v2.0.50727                       2.0.50727.4927
v3.0                             3.0.30729.4926
Windows Communication Foundation 3.0.4506.4926
Windows Presentation Foundation  3.0.6920.4902
v3.5                             3.5.30729.4926
Client                           4.8.04084      528372
Full                             4.8.04084      528372
Client                           4.0.0.0
```

### PR DESCRIPTION
**Pull request by andreasjordan**
## Type of Change

 - [x] Bug fix (non-breaking change, fixes #8275 )
 - [ ] New feature (non-breaking change, adds functionality, fixes # )
 - [ ] Breaking change (effects multiple commands or functionality, fixes # )
 - [ ] Ran manual Pester test and has passed (`.\tests\manual.pester.ps1`)
 - [ ] Adding code coverage to existing functionality
 - [ ] Pester test is included
 - [ ] If new file reference added for test, has is been added to github.com/dataplat/appveyor-lab ?
 - [ ] Unit test is included
 - [ ] Documentation
 - [ ] Build system

This is the new download-link for CU8 of SQL Server 2019:
https://catalog.s.download.windowsupdate.com/c/msdownload/update/software/updt/2020/10/sqlserver2019-kb4577194-x64_a09e2537b854ae384d965e998e53ce33cdc34f16.exe

So it looks like they have added "catalog.s." in from of the URL.

### CODE REVIEW

**Comment by potatoqualitee** [comment]
you're awesome, thank you! gonna reenable those tests

**Comment by andreasjordan** [comment]
We have more issues with the command. It sometimes works - and sometimes not. Looks like the webserver does not give the same answer every time...

**Comment by andreasjordan** [comment]
Current state:
```
VERBOSE: [12:15:45][Get-DbaKbUpdate] Downloading detailed information for updateid=0c84df7a-e685-466c-a545-a24de5ad2601
VERBOSE: GET https://www.catalog.update.microsoft.com/ScopedViewInline.aspx?updateid=0c84df7a-e685-466c-a545-a24de5ad2601 with 0-byte payload
VERBOSE: received 27804-byte response of content type text/html; charset=utf-8
VERBOSE: [12:15:46][Get-Info] Failed to get info with pattern '<span id="ScopedViewHandler_labelClassification_Separator" class="labelTitle">'
VERBOSE: [12:15:46][Get-Info] Failed to get info with pattern '<span id="ScopedViewHandler_labelSupportedProducts_Separator" class="labelTitle">'
VERBOSE: [12:15:46][Get-Info] Failed to get info with pattern '<span id="ScopedViewHandler_labelSecurityBulliten_Separator" class="labelTitle">'
VERBOSE: [12:15:46][Get-Info] Failed to get info with pattern '<span id="ScopedViewHandler_labelUninstallNotes_Separator" class="labelTitle">'
VERBOSE: [12:15:46][Get-Info] Failed to get info with pattern '<span id="ScopedViewHandler_labelUninstallSteps_Separator" class="labelTitle">'
```

**Comment by andreasjordan** [comment]
There is no systematic error, the web server just does not provide the correct data from time to time. What do we do in this case? I would simply issue a warning.

**Comment by andreasjordan** [comment]
I think this is all we can do for now. If someone has a contact at the webserver team at microsoft we can try to get more information about this issue.

I vote for releasing this as soon as possible to be able to use the commands again.

**Comment by potatoqualitee** [comment]
Thanks so much! will release now

**Pull request merged**
