### PR TITLE
Backup-DbaDatabase - Avoid reading database

### LINKED ISSUE #8209: Backup-DbaDatabase
### Verified issue does not already exist?

Yes

### What error did you receive?

Not really an error, but more function didn't work as expected based upon using Microsoft SQL Module. 

WARNING: [08:27:11][Backup-DbaDatabase] Backup Failed | The target database, 'Columbus_Master', is participating in an availability group and is currently not accessible for queries. Either data movement is suspen
ded or the availability replica is not enabled for read access. To allow read-only access to this and other databases in the availability group, enable read access to one or more secondary availability replicas in
 the group.  For more information, see the ALTER AVAILABILITY GROUP statement in SQL Server Books Online.

### Steps to Reproduce

Running the following command on the secondary SQL Server

Backup-DbaDatabase -SqlInstance $Server -Database $DBName -FilePath ($DBBackupFile+".bak") -Type Full -CopyOnly -CompressBackup

### Are you running the latest release?

Yes

### Other details or mentions

To standardize our process with using DbaTools as our primary module, I was converting my backup script to use DbaTools and during the testing I got the warning message that didn't allow the backup on the secondary SQL Server.  

Backup-DbaDatabase -SqlInstance $Server -Database $DBName -FilePath ($DBBackupFile+".bak") -Type Full -CopyOnly -CompressBackup

WARNING: [08:27:11][Backup-DbaDatabase] Backup Failed | The target database, 'Columbus_Master', is participating in an availability group and is currently not accessible for queries. Either data movement is suspen
ded or the availability replica is not enabled for read access. To allow read-only access to this and other databases in the availability group, enable read access to one or more secondary availability replicas in
 the group.  For more information, see the ALTER AVAILABILITY GROUP statement in SQL Server Books Online.

Before I take action on the SQL servers, I want to pass this on to the group that: 

Backup-SqlDatabase -ServerInstance $Server -Database $DBName -BackupFile ($DBBackupFile+".bak") -CopyOnly

Works fine, 

### What PowerShell host was used when producing this error

Windows PowerShell ISE (powershell_ise.exe)

### PowerShell Host Version

Name                           Value                                                                                                                                                                                
----                           -----                                                                                                                                                                                
PSVersion                      5.1.17763.1                                                                                                                                                                          
PSEdition                      Desktop                                                                                                                                                                              
PSCompatibleVersions           {1.0, 2.0, 3.0, 4.0...}                                                                                                                                                              
BuildVersion                   10.0.17763.1                                                                                                                                                                         
CLRVersion                     4.0.30319.42000                                                                                                                                                                      
WSManStackVersion              3.0                                                                                                                                                                                  
PSRemotingProtocolVersion      2.3                                                                                                                                                                                  
SerializationVersion           1.1.0.1                                                                                                                                                                              

### SQL Server Edition and Build number

Microsoft SQL Server 2019 (RTM-CU9) (KB5000642) - 15.0.4102.2 (X64)   Jan 25 2021 20:16:12   Copyright (C) 2019 Microsoft Corporation  Enterprise Edition (64-bit) on Windows Server 2019 Standard 10.0 <X64> (Build 17763: ) (Hypervisor) 

### .NET Framework Version

.NET Framework 4.7.3740.0

### PR DESCRIPTION
**Pull request by ACALVETT**
## Type of Change

 - [X] Bug fix (non-breaking change, fixes #8209  )
 - [ ] New feature (non-breaking change, adds functionality, fixes # )
 - [ ] Breaking change (effects multiple commands or functionality, fixes # )
 - [ ] Ran manual Pester test and has passed (`.\tests\manual.pester.ps1`)
 - [ ] Adding code coverage to existing functionality
 - [ ] Pester test is included
 - [ ] If new file reference added for test, has is been added to github.com/dataplat/appveyor-lab ?
 - [ ] Unit test is included
 - [ ] Documentation
 - [ ] Build system

### Purpose
Don't try to read the database to retrieve file locations as it fails if not readable.

### Approach
Uses the backup history instead which is already retrieved.

### CODE REVIEW

**Comment by andreasjordan** [comment]
Interesting approach, @Stuart-Moore should have a look at this.

**Comment by andreasjordan** [comment]
Tests complain: Backup-DbaDatabase.ps1 is not compliant with the OTBS formatting style. Please run Invoke-DbatoolsFormatter against the failing file and commit the changes.

But I don't see where the problem is - please use Invoke-DbatoolsFormatter.

**Comment by ACALVETT** [comment]
Thanks Andreas, the formatter caught the problem which was a missing space.

**Comment by potatoqualitee** [comment]
Pretty brilliant solution! I cannot see any downsides and all tests pass 🤔

**Comment by Stuart-Moore** [comment]
Using -Last could be more efficient as it filters the main SQL query. Would speed things up for the animals that don't expunge their backup history, as it would return less data to the function to be filtered

Happy with the approach 👍

**Comment by potatoqualitee** [comment]
haha thank you stuart

**Pull request merged**
