### PR TITLE
Get-DbaEstimatedCompletionTime - Only show queries that provide estimated completion time

### LINKED ISSUE #8266: Add parameter to Get-DbaEstimatedCompletionTime to filter tasks that actually report progress
### Summarize Functionality

Most commands in T-SQL don't populate percent_complete or estimated_completion_time in sys.dm_exec_requests. As written, Get-DbaEstimatedCompletionTime returns information for all sessions with an active request. On a busy server, that could be thousands of rows.

My proposal is to either:

* Change the default behavior of the cmdlet to exclude rows `WHERE percent_complete = 0 AND estimated_completion_time  = 0` and add a flag if the cmdlet caller wants the current behavior (i.e. "return information for all active sessions").
* Add a flag that allows the above behavior to be requested by the cmdlet caller.

### Is there a command that is similiar or close to what you are looking for?

No

### Technical Details

The internals of the cmdlet currently just run a query against sys.dm_exec_requests so inlining a WHERE clause based on the parameter in there should be fairly straightforward.

### PR DESCRIPTION
**Pull request by andreasjordan**
## Type of Change

 - [ ] Bug fix (non-breaking change, fixes # )
 - [ ] New feature (non-breaking change, adds functionality, fixes # )
 - [x] Breaking change (effects multiple commands or functionality, fixes #8266 )
 - [ ] Ran manual Pester test and has passed (`.\tests\manual.pester.ps1`)
 - [ ] Adding code coverage to existing functionality
 - [ ] Pester test is included
 - [ ] If new file reference added for test, has is been added to github.com/dataplat/appveyor-lab ?
 - [ ] Unit test is included
 - [ ] Documentation
 - [ ] Build system

### CODE REVIEW

**Comment by andreasjordan** [comment]
Test fail, because we don't test for a query with estimated completion time but only for the SELECT that is issued by the command itself - which now is filtered out. We would have a issue an async DBCC CHECKDB within the test...

**Comment by andreasjordan** [comment]
`WAITFOR DELAY` does not create an estimated completion time. I think the main problem is to start something async. We will maybe have to use a job for that.

**Comment by andreasjordan** [comment]
This worked in my lab:

```
$server = Connect-DbaInstance -SqlInstance sql01
$biggestDatabase = Get-DbaDatabase -SqlInstance $server | Sort-Object SizeMB | Select-Object -Last 1 -ExpandProperty Name
$null = New-DbaAgentJob -SqlInstance $server -Job checkdb
$null = New-DbaAgentJobStep -SqlInstance $server -Job checkdb -StepName checkdb -Subsystem TransactSql -Command "DBCC CHECKDB('$biggestDatabase')"
$null = Start-DbaAgentJob -SqlInstance $server -Job checkdb
$result = Get-DbaEstimatedCompletionTime -SqlInstance $server
$null = Remove-DbaAgentJob -SqlInstance $server -Job checkdb -Confirm:$false
```

But we need a big enough database. What Databases are installed on AppVeyer?

**Comment by andreasjordan** [comment]
That seems to work, thanks.

**Comment by potatoqualitee** [comment]
Woo!

**Pull request merged**
