### PR TITLE
Convert-SIDToUserName was throwing an exception with orphaned SIDs

### LINKED ISSUE #8118: Get-DbaPrivilege Produces No Output in Remote Session
### Verified issue does not already exist?

Yes

### What error did you receive?

Some or all identity references could not be translated.
    + CategoryInfo          : NotSpecified: (SVDSQLMORPH1:String) [], Exception
    + FullyQualifiedErrorId : dbatools_Get-DbaPrivilege

### Steps to Reproduce

Running remotely with -ComputerName returns the appropriate information.
image

Running in a remote session does not return any information and errors that the identity references could not be translated. The same happens when running remotely with pwsh.
image

### Are you running the latest release?

Yes

### Other details or mentions

The same error occurs when running locally, but does not prevent results from being displaying. When running remotely, no results are displayed. I understand there may be an unknown/orphaned SID on the system but I would expect the result to be the same whether running locally or remotely.

### What PowerShell host was used when producing this error

PowerShell Core (pwsh.exe), Windows PowerShell (powershell.exe)

### PowerShell Host Version

Local Session
```
Name                           Value
----                           -----
PSVersion                      7.1.3
PSEdition                      Core
GitCommitId                    7.1.3
OS                             Microsoft Windows 10.0.17763
Platform                       Win32NT
PSCompatibleVersions           {1.0, 2.0, 3.0, 4.0…}
PSRemotingProtocolVersion      2.3
SerializationVersion           1.1.0.1
WSManStackVersion              3.0
```

Remote Session Windows PowerShell
```
Name                           Value
----                           -----
PSVersion                      5.1.17763.2268
PSEdition                      Desktop
PSCompatibleVersions           {1.0, 2.0, 3.0, 4.0...}
BuildVersion                   10.0.17763.2268
CLRVersion                     4.0.30319.42000
WSManStackVersion              3.0
PSRemotingProtocolVersion      2.3
SerializationVersion           1.1.0.1
```

Remote Session PowerShell Core
```
Name                           Value
----                           -----
PSEdition                      Core
PSRemotingProtocolVersion      2.3
Platform                       Win32NT
PSCompatibleVersions           {1.0, 2.0, 3.0, 4.0...}
OS                             Microsoft Windows 10.0.17763
PSVersion                      7.1.3
WSManStackVersion              3.0
GitCommitId                    7.1.3
SerializationVersion           1.1.0.1
```

### SQL Server Edition and Build number

N/A

### .NET Framework Version

Local Session: 5.0.4
Remote Session Windows PowerShell: 4.8.4420.0
Remote Session PowerShell Core: 5.0.4

### PR DESCRIPTION
**Pull request by awickham10**
## Type of Change

 - [x] Bug fix (non-breaking change, fixes #8118 )
 - [ ] New feature (non-breaking change, adds functionality, fixes # )
 - [ ] Breaking change (effects multiple commands or functionality, fixes # )
 - [ ] Ran manual Pester test and has passed (`.\tests\manual.pester.ps1`)
 - [ ] Adding code coverage to existing functionality
 - [ ] Pester test is included
 - [ ] If new file reference added for test, has is been added to github.com/dataplat/appveyor-lab ?
 - [ ] Unit test is included
 - [ ] Documentation
 - [ ] Build system

### Purpose
Resolve error when running command locally and not from a remote session.

```
Some or all identity references could not be translated.
+ CategoryInfo : NotSpecified: (MYCOMPUTERNAME:String) [], Exception
+ FullyQualifiedErrorId : dbatools_Get-DbaPrivilege
```

### Approach
Wrap SID translation in try/catch. If an error is thrown, return no username.

### Commands to test
Get-DbaPrivilege on a computer with an orphaned SID.

### CODE REVIEW

**Comment by andreasjordan** [comment]
What about returning `$SID` instead of `$null`? `Get-Acl` also returns the SIDs of unresolvable accounts.

And what about using `@'` and `'@` instead of `@"` and `"@`? That way we don't need all the backticks to escape the dollar signs.

And maybe removing the space after `Translate(`?

But I like the solution in general - everything else would probably be to complicated.

**Comment by awickham10** [comment]
Just pushed new version with changes requested.

**Review by andreasjordan — APPROVED** [review]
Thanks, looks good to me.

**Comment by potatoqualitee** [comment]
Thank you both 🙇🏼 !

**Pull request merged**
