### PR TITLE
Backup-DbaDatabase : add a new switch parameter "NoAppendDbNameInPath" to prevent dbname systematically appended at the end of backup path

### PR DESCRIPTION
**Pull request by rferraton**
## Type of Change

 - [ ] Bug fix (non-breaking change, fixes # )
 - [x] New feature (non-breaking change, adds functionality, fixes # )
 - [ ] Breaking change (affects multiple commands or functionality, fixes # )
 - [ ] Ran manual Pester test and has passed (`.\tests\manual.pester.ps1`)
 - [ ] Adding code coverage to existing functionality
 - [x] Pester test is included
 - [ ] If new file reference added for test, has is been added to github.com/dataplat/appveyor-lab ?
 - [ ] Unit test is included
 - [x] Documentation
 - [ ] Build system

### Purpose

1. Avoid to force the directory path to finish with the dbname whereas the path can be variabilized with -ReplaceInName and dbname token
2. When the dbname is long the directory path length limit (259 characters) imposed by MSSQL Engine can be reach very easily when dbname is used twice in the path
3. To allow to stick with Ola Hallengren default backup path
4. Solve feature request [#9346](https://github.com/dataplat/dbatools/issues/9346)

### Approach
Add a new switch variable that will avoid breaking changes to existing backup scripts using Backup-DbaDatabase but will allow to prevent the dbname to be systematicaly added at the end of the path

### Commands to test
```powershell
Backup-DbaDatabase -SqlInstance localhost -Database TESTDATABASE_ABC_1eed02d4-f58b-4110-9cee-78c2fa65123a_123456789012345678901234567890 -Type Full -CompressBackup -Checksum -Verify -FileCount 1 -Path "D:\MSSQL\BACKUPS\servername\instancename\dbname\backuptype" -FilePath "servername_dbname_backuptype_timestamp.bak" -TimeStampFormat "yyyyMMdd_HHmm" -ReplaceInName -CreateFolder -WarningVariable WarningVariable -OutVariable BackupResults -EnableException -NoAppendDbNameInPath
```

### Screenshots
2024-05-13_15h04_34

### CODE REVIEW

**Comment by wsmelton** [comment]
Why is this needed? I don't see any issue linking the feature being requested.

**Comment by wsmelton** [comment]
> breaking changes to existing backup scripts

Who's backup scripts?

**Comment by niphlod** [comment]
looks good, may be a niche case, and would probably benefit from a specific test to make sure no regressions are introduced.

**Comment by rferraton** [comment]
Thanks/Merci !

**Pull request merged**
