### PR TITLE
Get-DbaPermission does not process DENY

### PR DESCRIPTION
**Pull request by pollusb**
## Type of Change

 - [x] Bug fix (non-breaking change, fixes # )
 - [ ] New feature (non-breaking change, adds functionality, fixes # )
 - [ ] Breaking change (affects multiple commands or functionality, fixes # )
 - [ ] Ran manual Pester test and has passed (`.\tests\manual.pester.ps1`)
 - [ ] Adding code coverage to existing functionality
 - [ ] Pester test is included
 - [ ] If new file reference added for test, has is been added to github.com/dataplat/appveyor-lab ?
 - [ ] Unit test is included
 - [ ] Documentation
 - [ ] Build system

### Purpose

Resolve wrong GrantStatement

### Commands to test
```powershell
PS> $perm = Get-DbaPermission @splat -ExcludeSystemObjects 
PS> $perm|? PermState -eq DENY|select -f 1 PermState,PermissionName,GrantStatement

PermState      : DENY
PermissionName : DELETE
GrantStatement : GRANT DELETE ON [dbo].[table1] TO [user1]

PS> $perm = Get-DbaPermission @splat -ExcludeSystemObjects 
PS> $perm|? PermState -eq DENY|select -f 1 PermState,PermissionName,GrantStatement

PermState      : DENY
PermissionName : DELETE
GrantStatement : DENY DELETE ON [dbo].[table1] TO [user1]
```

### CODE REVIEW

**Comment by pollusb** [comment]
What can I do to help it pass the last check?

Thanks

**Review by niphlod — APPROVED** [review]

**Comment by niphlod** [comment]
hi  @pollusb , failure was seemingly unrelated. I restarted the CI process.
PS: If I'm not around just pushing a new commit will trigger the CI automatically.

**Comment by pollusb** [comment]
Thanks for the tip

Le ven. 5 juill. 2024 03:00, Simone Bizzotto ***@***.***> a
écrit :

**Review by Imran-imtiaz48 — COMMENTED** [review]
Review
1.	Change in GrantStatement:
o	Old Code: Uses 'GRANT ' + permission_name.
o	New Code: Uses state_desc + ' ' + permission_name.
Improvements Needed
1.	Clarity and Intent:
o	Ensure that the change from 'GRANT ' + permission_name to state_desc + ' ' + permission_name accurately reflects the intent and requirement of the GrantStatement. Verify if state_desc provides necessary additional context or if it should be explicitly defined in the statement.
2.	Consistency:
o	Check if similar changes are required in other parts of the codebase or queries to maintain consistency in naming and formatting.
3.	Documentation:
o	Document the rationale behind the change, especially if it affects how permissions are represented or queried.
Summary
The change in GrantStatement from concatenating 'GRANT ' + permission_name to using state_desc + ' ' + permission_name suggests a potential enhancement in clarity or functionality. Ensure that this change aligns with the overall query requirements and is well-documented for future maintenance and understanding.

**Comment by pollusb** [comment]
@Imran-imtiaz48 
Are you asking something from me? 
If so, please clarify exactly what you expect from me.

Thanks

**Comment by pollusb** [comment]
The actual code does not provide the right TSQL command. On database objects, you can `GRANT` or `DENY` an ACTION on an OBJECT to a USER. Let's use this example:
`GRANT SELECT on dbo.Table1 to User1`
When you ask `Get-DbaPermission` to provide 'GrantStatement' it will resolve correctly. But if you try to DENY it then the actual rationale is wrong.
`DENY SELECT on dbo.Table1 to User1` would produce `GRANT SELECT on dbo.Table1 to User1` in column GrantStatement.

I know that the column name is GrantStatement and RevokeStatement. We shouldn't create a new column DenyColumn because you can REVOKE both GRANT or DENY in the same way.
```sql
GRANT SELECT on dbo.Table1 to User1 -- would give access
DENY SELECT on dbo.Table1 to User1 -- would revoke the precedent grant and deny access
REVOKE SELECT on dbo.Table1 to User1 -- would revoke the precedent deny
```

**Comment by potatoqualitee** [comment]
@pollusb please ignore the review, it's AI generated. I appreciate AI but it needs to be implemented with intent and after a discussion with the team.

**Comment by potatoqualitee** [comment]
and thank you! 🥳

**Comment by pollusb** [comment]
Thanks to you.

**Pull request merged**
