### PR TITLE
Update-DbaMaintenanceSolution - Fix for case-sensitive database name

### LINKED ISSUE #8598: Update-DbaMaintenanceSolution -database is case sensitive
### Verified issue does not already exist?

I have searched and found no existing issue

### What error did you receive?

When running "Update-DbaMaintenanceSolution" and providing an optional database name (we dont use master-database for this solution) it always throws the following error  IF we use the wrong case for the naming of the database. Since SQL Server isn't case sensitive with database naming, this is a quite odd problem which causes som problems if differens persons has set up their databases using different caseing scheme. 

```
ComputerName : serverXXXX
InstanceName : MSSQLSERVER
SqlInstance  : serverXXXX
Solution     : CommandExecute
Procedure    : CommandExecute
IsUpdated    : False
Results      : Procedure not installed
```

But if I use the correct casing on the database name it will run through as expected. 

Example:

`Databasename: **MaintDB**`

Wont't work:
`Update-DbaMaintenanceSolution -SqlInstance . -Database maintdb `

Will work: 
` Update-DbaMaintenanceSolution -SqlInstance . -Database MaintDB`

### Steps to Reproduce

```powershell
# provide your command(s) executed pertaining to dbatools
# please include variable values (redacted or fake if needed) for reference
```
Must have an external maintenance database such as MaintDB 

Run: `Update-DbaMaintenanceSolution -SqlInstance . -Database maintdb ` 

note the WRONG caseing! You will not get this error on a database using correct caseing. 

### Please confirm that you are running the most recent version of dbatools

Major  Minor  Build  Revision
-----  -----  -----  --------
1      1      136    -1

### Other details or mentions

_No response_

### What PowerShell host was used when producing this error

Windows PowerShell (powershell.exe), VS Code (terminal)

### PowerShell Host Version

Name                           Value                                                                                   
----                           -----                                                                                   
PSVersion                      5.1.19041.1682                                                                          
PSEdition                      Desktop                                                                                 
PSCompatibleVersions           {1.0, 2.0, 3.0, 4.0...}                                                                 
BuildVersion                   10.0.19041.1682                                                                         
CLRVersion                     4.0.30319.42000                                                                         
WSManStackVersion              3.0                                                                                     
PSRemotingProtocolVersion      2.3                                                                                     
SerializationVersion           1.1.0.1                                                                                 

### SQL Server Edition and Build number

Different versions in our estate, same error.

### .NET Framework Version

PSChildName Version
----------- -------
Client      4.8.04084
Full        4.8.04084
Client      4.0.0.0

### PR DESCRIPTION
**Pull request by andreasjordan**
## Type of Change

 - [x] Bug fix (non-breaking change, fixes #8598 )
 - [ ] New feature (non-breaking change, adds functionality, fixes # )
 - [ ] Breaking change (effects multiple commands or functionality, fixes # )
 - [ ] Ran manual Pester test and has passed (`.\tests\manual.pester.ps1`)
 - [ ] Adding code coverage to existing functionality
 - [ ] Pester test is included
 - [ ] If new file reference added for test, has is been added to github.com/dataplat/appveyor-lab ?
 - [ ] Unit test is included
 - [ ] Documentation
 - [ ] Build system

See issue for details.

### CODE REVIEW

**Comment by potatoqualitee** [comment]
Wild. Can you please report this to Microsoft? I believe using the hash is like 100x faster.

**Comment by potatoqualitee** [comment]
Looks good, thank you so much! Nice to have you back 🤩

**Comment by andreasjordan** [comment]
Reported: https://github.com/microsoft/sqlmanagementobjects/issues/115

**Comment by potatoqualitee** [comment]
awesome, thanks so much! in the future, with the library publishing change, it'll be nice to incorporate their changes as they make them

**Comment by frodr1k** [comment]
THsank you guys!

**Pull request merged**
