### PR TITLE
Update dbatools-buildref-index.json security patches 2019, 2022

### PR DESCRIPTION
**Pull request by MikeyBronowski**
## Type of Change

 - [ ] Bug fix (non-breaking change, fixes # )
 - [ ] New feature (non-breaking change, adds functionality, fixes # )
 - [ ] Breaking change (affects multiple commands or functionality, fixes # )
 - [ ] Ran manual Pester test and has passed (`.\tests\manual.pester.ps1`)
 - [ ] Adding code coverage to existing functionality
 - [ ] Pester test is included
 - [ ] If new file reference added for test, has is been added to github.com/dataplat/appveyor-lab ?
 - [ ] Unit test is included
 - [x] Documentation
 - [ ] Build system

### Purpose

[Security patch for SQL 2019 CU25](https://support.microsoft.com/en-us/help/5036335)
[Security patch for SQL 2019 RTM](https://support.microsoft.com/en-us/help/5035434)
[Security patch for SQL 2022 CU12](https://support.microsoft.com/en-us/help/5036343)
[Security patch for SQL 2022 RTM](https://support.microsoft.com/en-us/help/5035432)

### CODE REVIEW

**Review by niphlod — APPROVED** [review]
failures on appveyor are unrelated

**Comment by potatoqualitee** [comment]
Thank you both 🙇🏼  will merge shortly

**Comment by potatoqualitee** [comment]
I'm unsure why the repo size test passed, but @MikeyBronowski -- the current .git repo is 72MB but the repo in this PR is 300+ MB.  Can you please delete your dbatools folder, reclone and resubmit PR?

**Comment by MikeyBronowski** [comment]
> I'm unsure why the repo size test passed, but @MikeyBronowski -- the current .git repo is 72MB but the repo in this PR is 300+ MB.  Can you please delete your dbatools folder, reclone and resubmit PR? 



I made changes through the web interface. Went straight to the file in dataplat repo and it created a branch under my fork.

**Comment by MikeyBronowski** [comment]
Actually, I did it online, but used that Vs code feature in the browser. I think it was the first time I did it this way so maybe my fork was not up to date.

**Comment by potatoqualitee** [comment]
ahh yeah, might need to refork?

**Comment by MikeyBronowski** [comment]
I wonder if that happened before (web interface but no Vs code) as I usually update those ref details this way.

**Comment by wsmelton** [comment]
@MikeyBronowski using the web UI you can go to your fork and tell it to update it to upstream
image

**Comment by MikeyBronowski** [comment]
> @MikeyBronowski using the web UI you can go to your fork and tell it to update it to upstream
> image
> 

That's what I did after Chrissy's comment.

Previously I never updated the branch when adding changes through the GitHub web interface, so either this was unnoticed before or change done via web vs code did it differently (that's the first time I used web vs code here.

**Pull request closed without merging**
