### PR TITLE
New-DbaDiagnosticAdsNotebook - remove extra bracket

### LINKED ISSUE #8313: New-DbaDiagnosticAdsNotebook contains an extra curly brace at the bottom '}' makes it invalid JSON
### Verified issue does not already exist?

Yes

### What error did you receive?

No error creating the diagnostic ADS notebook and it can be opened in ADS, but when using Invoke-SQLNotebook it throws an error that it is invalid JSON.  I checked it out and it is indeed an extra closing } brace.  Once I removed that curly brace I could invoke-sqlnotebook without error of the JSON.

### Steps to Reproduce

```powershell
# provide your command(s) executed pertaining to dbatools
# please include variable values (redacted or fake if needed) for reference
```
Create a new diagnostic ADS notebook with New-DbaDiagnosticAdsNotebook
Import the SqlServer module and attempt to Invoke-SqlNotebook and it will throw an error about invalid JSON

### Are you running the latest release?

Yes

### Other details or mentions

_No response_

### What PowerShell host was used when producing this error

Windows PowerShell (powershell.exe)

### PowerShell Host Version

Name                           Value                                                                                   
----                           -----                                                                                   
PSVersion                      5.1.22000.613                                                                           
PSEdition                      Desktop                                                                                 
PSCompatibleVersions           {1.0, 2.0, 3.0, 4.0...}                                                                 
BuildVersion                   10.0.22000.613                                                                          
CLRVersion                     4.0.30319.42000                                                                         
WSManStackVersion              3.0                                                                                     
PSRemotingProtocolVersion      2.3                                                                                     
SerializationVersion           1.1.0.1                                                                                 

### SQL Server Edition and Build number

Did not need a SQL Server for this to fail.

### .NET Framework Version

PSChildName Version
----------- -------
Client      4.8.04161
Full        4.8.04161
Client      4.0.0.0

### PR DESCRIPTION
**Pull request by potatoqualitee**
Fixes #8313

### CODE REVIEW

**Comment by potatoqualitee** [comment]
```
New-DbaDiagnosticAdsNotebook -TargetVersion 2019 -Path c:\temp\2019.ipynb

Install-Module SqlServer -AllowClobber
Import-Module SqlServer
Invoke-SqlNotebook -ServerInstance localhost -InputFile c:\temp\2019.ipynb -OutputFile c:\temp\test.ipynb
```

image

I received a similar issue so I tried to add an encoding thing and it didnt fix :/

**Review by andreasjordan — APPROVED** [review]
Looks good.

Update: Sorry, only the brackets look goods now...

**Comment by andreasjordan** [comment]
This is the BOM, because on Windows you get a BOM by xdefault.

More info: https://stackoverflow.com/questions/5596982/using-powershell-to-write-a-file-in-utf-8-without-the-bom

I tried to change line 158 from `$preamble | Out-File $Path` to `[IO.File]::WriteAllLines($Path, $preamble)` and that created UTF-8 without BOM.

**Comment by spaghettidba** [comment]
Sorry, I had no idea how to amend the code in here, so I created a new PR: https://github.com/dataplat/dbatools/pull/8347
It solves the encoding issue (thanks @andreasjordan!!) and also fixes a weird bug in both vscode and azdatastudio that requires "metadata" properties for all cells (wasn't needed before).

**Comment by potatoqualitee** [comment]
thank you both! Closing this one

**Pull request closed without merging**
