### PR TITLE
Copy-DbaSystemDbUserObject - Create schema with correct owner

### LINKED ISSUE #9011: Start-DBAMigration changes two msdb schema authorizations to dbo in the target instance
### Verified issue does not already exist?

I have searched and found no existing issue

### What error did you receive?

Bug - Start-DbaMigration apparently migrates schemas, but doesn't copy over the Authorization value.  In msdb there are a couple of schemas that are referenced in MS script msdb110_upgrade.sql that is part of Cumulative Update installs and after I run Start-Migration the schemas TargetServersRole and DatabaseMailUsersRole change authorizations to dbo, rather than TargetServersRole and DatabaseMailUsersRole which are the Authorization values in the Source instance.  All the instances that are the result of a Start-DbaMigration have been experiencing CU install failures with event errors citing the msdb110_upgrade.sql script and I have to drop the two schemas before the CU install will complete.  The only difference in msdb for the instances that fail compared to the ones that don't fail is the schema Authorizations.  I am using dbatools version 1.1.143 on SQL Server 2017 and 2019 on Windows.

### Steps to Reproduce

```powershell
# provide your command(s) executed pertaining to dbatools
# please include variable values (redacted or fake if needed) for reference
```
<# I start with both the source instance and the target instance having the same values for the msdb schemas DatabaseMailUserRole and TargetServersRole - and yes, the schema names appear to be Role names but that is how Microsoft has set these up.  In the Information_Schema.Schemata tale both the SCHEMA_NAME and SCHEMA_OWNER values are the same - the schema TargetServersRole, the SCHEMA_NAME is TargetServersRole and the SCHEMA_OWNER is TargetServersRole.  But after I run Start-DbaMigration with the following code, the SCHEMA_OWNER changes to dbo.  The same deal for the schema named DatabaseMailUserRole.  Note that the source instance and the target instance are on the same server and are the same SQL Server version.  This happens on both SQL 2017 and SQL 2019.    #>
$SourceInstance = 'SERVERName\InstanceName1'
$DestinationInstance = 'SERVERName\InstanceName2'

## Last migration step is to actually do the migration from the one instance to the other.  Excludes logins because we already took care of those.

    $ExcludeList = "SpConfigure", "Logins"

    $params = @{   
        Source = $SourceInstance
        Destination = $DestinationInstance
        UseLastBackup = $true
        Exclude = $ExcludeList
        DisableJobsOnDestination = $true
        ReuseSourceFolderStructure = $false
        Force = $true
        Whatif = $false
        }

    $params  # debug and display
    
    Start-DbaMigration @params -EnableException -Verbose -ErrorAction Stop | Format-Table Status,Type,Name -Wrap -AutoSize 

### Please confirm that you are running the most recent version of dbatools

I am running version 1.1.143.  I suspect that dbatools has been doing this Auth changing for years based on how for years I have needed to drop these schemas to get upgrades to work.

### Other details or mentions

_No response_

### What PowerShell host was used when producing this error

Windows PowerShell ISE (powershell_ise.exe)

### PowerShell Host Version

5.1.17763.3770

### SQL Server Edition and Build number

SQL 2019 15.0.4312.2
SQL 2017 14.0.3460.9

### .NET Framework Version

Client 4.8.03761
Full 4.8.03761
Client 4.0.0.0

### PR DESCRIPTION
**Pull request by andreasjordan**
## Please read -- recent changes to our repo
On November 10, 2022, [we removed some bloat from our repository (for the second and final time)](https://github.com/dataplat/dbatools/issues/8542). This change requires that all contributors reclone or refork their repo.

PRs from repos that have not been recently reforked or recloned will be closed and @potatoqualitee will cherry-pick your commits and open a new PR with your changes.

 - [ ] Please confirm you have the smaller repo (85MB .git directory vs 275MB or 110MB or 185MB .git directory)

## Type of Change

 - [x] Bug fix (non-breaking change, fixes #9011  )
 - [ ] New feature (non-breaking change, adds functionality, fixes # )
 - [ ] Breaking change (affects multiple commands or functionality, fixes # )
 - [ ] Ran manual Pester test and has passed (`.\tests\manual.pester.ps1`)
 - [ ] Adding code coverage to existing functionality
 - [ ] Pester test is included
 - [ ] If new file reference added for test, has is been added to github.com/dataplat/appveyor-lab ?
 - [ ] Unit test is included
 - [ ] Documentation
 - [ ] Build system

See issue for details.

@potatoqualitee - Please have a look if that line should be added to other transfers as well.

### CODE REVIEW

**Comment by potatoqualitee** [comment]
sooo happy you fixed this one, thank you! im unsure of the downsides. what if the owner does or does not exist?

**Comment by andreasjordan** [comment]
Is a schema without an owner possible?

**Comment by potatoqualitee** [comment]
sorry I meant what if the owner doesnt exist on the destination

**Comment by andreasjordan** [comment]
Ok, that would be a problem.

I generally have a problem with that command: Why would I want to use it? The schemas related to this bug here are "user objects" as per the IsSystemObject property in the object, but I think they are system objects as they will be there on the destination as they are part of the msdb core functionality. We just don't have a way to identify them by a rule. The command would copy over things like the command table for Ola or the version tables for the First Reposner Kit. But I would not have that copied over, because they would be created when installing those tools. So it's only for real user generated content that should not be in system databases. So I don't know what the best solution would be...

**Comment by potatoqualitee** [comment]
you know, i think if the owner doesnt exist, just let it error out naturally. better than the issue we've got going now.

LGTM ☑️

**Comment by gittroy** [comment]
Hello, I'm a new dbatools user (and new to this forum).  Is there a way to tell what version of dbatools will contain this fix?   I am seeing the same issue as: 
**_Start-DBAMigration changes two msdb schema authorizations to dbo in the target instance #9011_**
except it affects an additional six schemas in msdb (total 8 affected).  I am catching this just now as we are trying to update to CU21 and ran into the issue from: 
https://learn.microsoft.com/en-us/troubleshoot/sql/database-engine/install/windows/sqlserver-patching-issues#targetserversrole-schema-and-security-role

Below are the systems that all saw the same issue and the dbatools versions used on each:
VM#1:   2.0.4
VM#2:   2.0.4
VM#3:   1.1.145
VM#4:   1.1.146

**Comment by enolke** [comment]
I ran into this very same issue a handful of times over a year ago when
doing cumulative updates on migrated servers and it caused some gray hair
and delays.  If a new build could reduce the possibility  of dbatools
contributing to this in the future, I would really love it.
Thanks!
https://learn.microsoft.com/en-us/troubleshoot/sql/database-engine/install/windows/sqlserver-patching-issues#targetserversrole-schema-and-security-role

**Pull request merged**
