### PR TITLE
New-DbaDbTable - Fix some issues

### LINKED ISSUE #9198: New-DbaDbTable creates wrong datatype if no MaxLength specified
### Verified issue does not already exist?

I have searched and found no existing issue

### What error did you receive?

N/A

### Steps to Reproduce

```powershell
Import-Module DbaTools

$instance = 'MyInstance'
$database = 'MyDatabase'
$server = Connect-DbaInstance -SqlInstance $instance -Database $database -TrustServerCertificate

$tableName = 'BobTest'

$tabColumns = @()
$tabColumns += @{Name = 'Cola'; Type = 'nvarchar'; Nullable = $true; Default = 'Hello'; DefaultName = 'DF_Name_test5'}

Remove-DbaDbTable -SqlInstance $server -Database $database -Table $tableName -Confirm:$false
New-DbaDbTable -SqlInstance $server -Database $database -Name $tableName -ColumnMap $tabColumns

```

### Please confirm that you are running the most recent version of dbatools

2.1.5

### Other details or mentions

If I sepecify a MaxLength then a NVarchar column is created with the specified MaxLength.

if no MaxLength is specified then a varchar(max) column is created.

### What PowerShell host was used when producing this error

Windows PowerShell ISE (powershell_ise.exe)

### PowerShell Host Version

Name                           Value                                                                                                                                        
----                           -----                                                                                                                                        
PSVersion                      5.1.14393.6343                                                                                                                               
PSEdition                      Desktop                                                                                                                                      
PSCompatibleVersions           {1.0, 2.0, 3.0, 4.0...}                                                                                                                      
BuildVersion                   10.0.14393.6343                                                                                                                              
CLRVersion                     4.0.30319.42000                                                                                                                              
WSManStackVersion              3.0                                                                                                                                          
PSRemotingProtocolVersion      2.3                                                                                                                                          
SerializationVersion           1.1.0.1                                                                                                                                      

### SQL Server Edition and Build number

Microsoft SQL Server 2016 (SP3-GDR) (KB5029186) - 13.0.6435.1 (X64) 
	Jul 30 2023 19:53:42 
	Copyright (c) Microsoft Corporation
	Standard Edition (64-bit) on Windows Server 2016 Standard 10.0 <X64> (Build 14393: ) (Hypervisor)

### .NET Framework Version

PSChildName                      Version       
-----------                      -------       
v2.0.50727                       2.0.50727.4927
v3.0                             3.0.30729.4926
Windows Communication Foundation 3.0.4506.4926 
Windows Presentation Foundation  3.0.6920.4902 
v3.5                             3.5.30729.4926
Client                           4.8.03761     
Full                             4.8.03761     
Client                           4.0.0.0

### PR DESCRIPTION
**Pull request by andreasjordan**
## Type of Change

 - [x] Bug fix (non-breaking change, fixes #9198 )
 - [ ] New feature (non-breaking change, adds functionality, fixes # )
 - [ ] Breaking change (affects multiple commands or functionality, fixes # )
 - [ ] Ran manual Pester test and has passed (`.\tests\manual.pester.ps1`)
 - [ ] Adding code coverage to existing functionality
 - [ ] Pester test is included
 - [ ] If new file reference added for test, has is been added to github.com/dataplat/appveyor-lab ?
 - [ ] Unit test is included
 - [ ] Documentation
 - [ ] Build system

See issue for details.

### CODE REVIEW

**Comment by potatoqualitee** [comment]
this is a pretty big change, no? it no longer guesses. can it just guess better?

**Comment by andreasjordan** [comment]
Let me give a bit context about the changes. Inside of the process block, there are three changes.

The first change is just a syntax change and does not change any functionality.

The second change is the main fix and does change the functionality. It is inside an if block, so it is only executed, if `$sqlDbType` (which is `[Microsoft.SqlServer.Management.Smo.SqlDataType]$($column.Type)`) is one of the following: VarBinary, VarChar, NVarChar, Char, NChar. And additionally, there must not be a configured length - so we need the "Max"-Datatypes.
The old code uses the function `Get-SqlType` for a reason I do not know (more on that later). and because inside of the function there was no switch part for the char-Datatypes, the default of VarChar was used. So the function `Get-SqlType` is targeted on non-char-types like numbers and dates, and (in my oppinion) must not be used here. So I removed the use here.

The third change is a fix as well. In this code block, `$sqlDbType -eq 'Decimal'`, so we definitly have a decimal. So there is no "DecimalMax", and so there is no need to build this kind of datatype. The deleted line is most likely a copy-paste-bug.

After making these changes, the function `Get-SqlType` is not used anymore - so I deleted it. Even before my changes, the function was never called with datatypes like Int32 or Boolean. It was most likely just a leftover functionallity from an earlier version of the command.

**Comment by wsmelton** [comment]
The test for this command should be updated to show that the bug is fixed by this and still works for the other data types expected.

**Comment by potatoqualitee** [comment]
Thank you for the explanation 😊

**Comment by potatoqualitee** [comment]
and the test and the test suggestion haha

**Pull request merged**
