### PR TITLE
Get-DbaUserPermission - Refactoring again

### PR DESCRIPTION
**Pull request by andreasjordan**
Like in #8220, but this time without introducing a bug.

### CODE REVIEW

**Comment by andreasjordan** [comment]
Test should fail - just to see if test is effective.

Then I will fix the bug in the next commit.

**Comment by andreasjordan** [comment]
Ok, Test works:
image

Now let's fix the bug....

**Comment by Stuart-Moore** [comment]
That's fixed my issue 👍 (https://github.com/Stuart-Moore/sqlbitsdb1/runs/5520422771?check_suite_focus=true)

Thank you for sorting so quickly

**Comment by potatoqualitee** [comment]
awesome, thank you both so much! thank you for the quick turnaround too, @andreasjordan 🙇🏼

**Pull request merged**
