### PR TITLE
Write-DbaDbTableData: Fix for connections to Azure SQL Database with AccessToken

### LINKED ISSUE #9394: write-dbadbdatatable - cannot use connection created by connect-dbainstance
### Verified issue does not already exist?

I have searched and found no existing issue

### What error did you receive?

Login failed for user ''.
At line:97970 char:9
+         throw $records[0]
+         ~~~~~~~~~~~~~~~~~
    + CategoryInfo          : NotSpecified: (:) [], Exception
    + FullyQualifiedErrorId : dbatools_Write-DbaDbTableData

### Steps to Reproduce

$SQLCredential = get-credential #(this is a Service Principal / Azure application)

#this works and I get an object of type Microsoft.SqlServer.Management.Smo.Server in $server
$azureAccount = Connect-AzAccount -Credential $SQLCredential -ServicePrincipal -Tenant "redacted"
$azureToken = Get-AzAccessToken -ResourceUrl https://database.windows.net
$azureInstance = "<redacted>"
$azureDatabase = "<redacted>"
$server = Connect-DbaInstance -SqlInstance $azureInstance -Database $azureDatabase -AccessToken $azureToken

$StepID = 1
$StepStatus = "pending"
$ThingID = 999

#using the connection in $server, this successfully inserts a row into the database
$queryparams = @{
    Query = 'INSERT INTO redactedTable (StepID, StepStatus, ThingID) VALUES (@StepID, @StepStatus, @ThingID); SELECT SCOPE_IDENTITY() AS ID;'
    SqlParameter = @{ StepID = $StepId; StepStatus = $StepStatus; ThingID = $ThingID}
    SQLInstance = $server
}
Invoke-DbaQuery @queryparams -EnableException -ErrorAction Stop

#using the same connection in $server, neither one of the below Write-DBADBTableData commands work to insert a row
$Object = [pscustomObject]@{
    StepId = 2
    StepStatus = "pending"
    ThingID = 999
}

$writeparams = @{
        SQLInstance = $server
        Table = "redactedTable"
}

Write-DbaDbTableData @writeparams -InputObject $Object -EnableException -ErrorAction Stop

Write-DbaDbTableData -SqlInstance $server -table "redactedTable" -InputObject $object -EnableException -ErrorAction Stop
#Login failed for user ''.

### Please confirm that you are running the most recent version of dbatools

2.1.16

### Other details or mentions

Background:  I am connecting to an Azure SQL instance using an Azure Service Principal.
I connect to the instance using connect-DBAInstance and have a connection object in $server.
I am able to use $server as the value for the SQLInstance parameter for invoke-dbaquery and insert a row into the database.
I am not able to use that same instance of $server to insert a row using write-dbadbdatatable.
When I attempt it, I get the Login failed for user ''. message above.

### What PowerShell host was used when producing this error

Windows PowerShell ISE (powershell_ise.exe)

### PowerShell Host Version

Name                           Value                                                                                                                                                               
----                           -----                                                                                                                                                               
PSVersion                      5.1.20348.2400                                                                                                                                                      
PSEdition                      Desktop                                                                                                                                                             
PSCompatibleVersions           {1.0, 2.0, 3.0, 4.0...}                                                                                                                                             
BuildVersion                   10.0.20348.2400                                                                                                                                                     
CLRVersion                     4.0.30319.42000                                                                                                                                                     
WSManStackVersion              3.0                                                                                                                                                                 
PSRemotingProtocolVersion      2.3                                                                                                                                                                 
SerializationVersion           1.1.0.1                                                                                                                                                             

### SQL Server Edition and Build number

Microsoft SQL Azure (RTM) - 12.0.2000.8   May 11 2024 17:25:03   Copyright (C) 2022 Microsoft Corporation 

### .NET Framework Version

.NET Framework 4.8.4729.0

### PR DESCRIPTION
**Pull request by andreasjordan**
## Type of Change

 - [x] Bug fix (non-breaking change, fixes #9394 )
 - [ ] New feature (non-breaking change, adds functionality, fixes # )
 - [ ] Breaking change (affects multiple commands or functionality, fixes # )
 - [ ] Ran manual Pester test and has passed (`.\tests\manual.pester.ps1`)
 - [ ] Adding code coverage to existing functionality
 - [ ] Pester test is included
 - [ ] If new file reference added for test, has is been added to github.com/dataplat/appveyor-lab ?
 - [ ] Unit test is included
 - [ ] Documentation
 - [ ] Build system

See issue for details.

Also included in this pull request:
* Import-DbaCsv is now also supported, as I removed the all the `StatementTimeout 0` as they are the default anyway.
* Added a note in the documentation of AccessToken in Connect-DbaInstance on which commands are supported.

### CODE REVIEW

**Comment by andreasjordan** [comment]
`Import-DbaCsv` has the same problems - because it uses `Connect-DbaInstance` with ` -StatementTimeout 0`. That forces a `.ConnectionContext.Copy()` and that does not work with a token.

Will try to find a good solution for all of those commands.

**Comment by andreasjordan** [comment]
No, it's `$connContext.GetDatabaseConnection($Database)` that is the problem. Will have to test if this is needed...

**Comment by andreasjordan** [comment]
OK, I have to do more tests. Will do this in the next days...

**Comment by andreasjordan** [comment]
Not `.GetDatabaseConnection($Database)` is the problem, but `.ConnectionContext.Copy()`. This creates a new connection which fails in case the original connection was opened using AccessToken.

Bottom line: `$server` from `$server = Connect-DbaInstance ... -AccessToken` must not be changed by any `Connect-DbaInstance` inside of our commands.

**Comment by potatoqualitee** [comment]
Thank you, will take some time to review this one

**Comment by potatoqualitee** [comment]
Well it wont take a long time, just will check it out more deeply tomorrow 😅

**Comment by potatoqualitee** [comment]
im happy to merge this but how will we handle timeouts? i imagine the timeouts were adding for expected long-running queries. should we advise updating their configs?

**Comment by potatoqualitee** [comment]
And thank you 🙏🏼

**Comment by andreasjordan** [comment]
As StatementTimeout 0 was and is the default, there are no timeouts. So nothing was changed an that side and there should not be a problem.

**Pull request merged**
