### PR TITLE
Invoke-DbaDbLogShipping - Fix issues with Restore*Folder

### PR DESCRIPTION
**Pull request by andreasjordan**
## Type of Change

 - [x] Bug fix (non-breaking change, fixes # )
 - [ ] New feature (non-breaking change, adds functionality, fixes # )
 - [ ] Breaking change (effects multiple commands or functionality, fixes # )
 - [ ] Ran manual Pester test and has passed (`.\tests\manual.pester.ps1`)
 - [ ] Adding code coverage to existing functionality
 - [ ] Pester test is included
 - [ ] If new file reference added for test, has is been added to github.com/dataplat/appveyor-lab ?
 - [ ] Unit test is included
 - [ ] Documentation
 - [ ] Build system

Was reported on slack by Abhi.

I don't know what the idea of the per-database-subfolder was - but as it never worked, I removed it.
@sanderstad Do you have time to have a look?

### CODE REVIEW

**Comment by andreasjordan** [comment]
Message from Slack:

Hi All.I am trying to setup Logshipping for DB1 to the same server ( as DB1_Copy). But the new DB is getting restored to default DATA & LOG directory(to F drive, instead of N drive).Am I missing a parameter? Could you please help?

```
#Data & LOG location of DB1 : M drive
#Data & LOG location of DB1_Copy : N drive
# Instance Data & Log default location : F drive

# Configure Log Shipping 

$invokeDbaLogShippingSplat = @{   
SourceSqlInstance = 'sqlserver'    
DestinationSqlInstance = 'sqlserver'    
Database = 'DB1'  
SecondaryDatabaseSuffix = '_Copy'    
RestoreDataFolder='N:\Data\'     
RestoreLogFolder='N:\Log\'     
GenerateFullBackup=$true    
CompressBackup = $true
BackupNetworkPath = '\\sqlserver\share2'
BackupLocalPath = 'M:\share'
BackupScheduleFrequencySubdayType = 'Minutes'
BackupScheduleFrequencySubdayInterval = 5   
CopyDestinationFolder = 'M:\share'
CopyScheduleFrequencySubdayType = 'Minutes'
CopyScheduleFrequencySubdayInterval = 5
RestoreScheduleFrequencySubdayType = 'Minutes'
RestoreScheduleFrequencySubdayInterval = 5
NoRecovery = $true    
Force = $true
}
Invoke-DbaDbLogShipping @invokeDbaLogShippingSplat
```

**Comment by sanderstad** [comment]
The idea of the subfolder was to make sure that when the database had the same file names, you could still restore it on the same server.

**Comment by Abhilash1987** [comment]
Hi Andreas..I tested it but getting a different error now.  I am able to see the PreLogShipping backup file in the share I specified

PrimaryInstance   : sqlserver
SecondaryInstance : sqlserver
PrimaryDatabase   : Abhi
SecondaryDatabase : Abhi_Copy
Result            : Failed
Comment           : Something went wrong generating the full backup

**Comment by sanderstad** [comment]
What do you get when you run

```powershell
$error[0] | fl -force
```

**Comment by andreasjordan** [comment]
Thanks Sander for stepping in.

**Comment by Abhilash1987** [comment]
Please find the o/p of $error[0] | fl -force

Exception             : System.Management.Automation.CommandNotFoundException: The term 'Write-Message' is not recognized as the name of a cmdlet, function, script file, or 
                        operable program. Check the spelling of the name, or if a path was included, verify that the path is correct and try again.
                           at System.Management.Automation.CommandDiscovery.LookupCommandInfo(String commandName, CommandTypes commandTypes, SearchResolutionOptions 
                        searchResolutionOptions, CommandOrigin commandOrigin, ExecutionContext context)
                           at System.Management.Automation.CommandDiscovery.LookupCommandProcessor(String commandName, CommandOrigin commandOrigin, Nullable`1 useLocalScope)
                           at System.Management.Automation.ExecutionContext.CreateCommand(String command, Boolean dotSource)
                           at System.Management.Automation.PipelineOps.AddCommand(PipelineProcessor pipe, CommandParameterInternal[] commandElements, CommandBaseAst 
                        commandBaseAst, CommandRedirection[] redirections, ExecutionContext context)
                           at System.Management.Automation.PipelineOps.InvokePipeline(Object input, Boolean ignoreInput, CommandParameterInternal[][] pipeElements, 
                        CommandBaseAst[] pipeElementAsts, CommandRedirection[][] commandRedirections, FunctionContext funcContext)
                           at System.Management.Automation.Interpreter.ActionCallInstruction`6.Run(InterpretedFrame frame)
                           at System.Management.Automation.Interpreter.EnterTryCatchFinallyInstruction.Run(InterpretedFrame frame)
TargetObject          : Write-Message
CategoryInfo          : ObjectNotFound: (Write-Message:String) [], CommandNotFoundException
FullyQualifiedErrorId : CommandNotFoundException
ErrorDetails          : 
InvocationInfo        : System.Management.Automation.InvocationInfo
ScriptStackTrace      : at Invoke-DbaDbLogShipping<End>, <No file>: line 1683
                        at <ScriptBlock>, <No file>: line 23
PipelineIterationInfo : {}
PSMessageDetails      :

**Comment by sanderstad** [comment]
Well that error does not make much sense because that command is being used throughout the command and other commands as well.

Can you run the command for initialing the log shipping with -Verbose so we can see what the command does in the background?

**Comment by Abhilash1987** [comment]
Thanks Sander,  I could execute the script successfully but DB still gets created on the default location. Please find the logs attached.
[logshipping_PS.txt](https://github.com/dataplat/dbatools/files/8026012/logshipping_PS.txt)

**Comment by andreasjordan** [comment]
I just pushed a new commit to the branch which added some more verbose messages. This way we can prove that the new code path is executed.

**Comment by andreasjordan** [comment]
But your verbose output is missing "Testing database restore" which tells me that you don't run this branch here.
You could try to find the code for Invoke-DbaDbLogShipping inside of the allcomands.ps1 and replace it by the code from this branch. Otherwise you need to make sure to import with the full path like `Import-Module C:\GitHub\dbatools\dbatools.psm1`.

**Comment by Abhilash1987** [comment]
Hi Andreas, Thanks for providing the detailed steps. I tested the new code & it worked perfectly :-) Thanks again for the quick fix & help.

**Comment by potatoqualitee** [comment]
Hey all -- does @Abhilash1987's comment mean this is good and can be merged?

**Comment by andreasjordan** [comment]
I think so.

**Pull request merged**
