### PR TITLE
New-DbaAgentSchedule: Fix issues with testing for correct dates and times

### LINKED ISSUE #9388: New-DbaAgentSchedule flags an error with a start time before 10000?
### Verified issue does not already exist?

No, I did not search

### What error did you receive?

![image](https://github.com/dataplat/dbatools/assets/20241184/4bb42e8c-89ff-4479-b15f-becc6decc711)


### Steps to Reproduce

```powershell
# provide your command(s) executed pertaining to dbatools
# please include variable values (redacted or fake if needed) for reference
```

 $dailymaintenancestarttime = 000000 #all of the daily maintenance jobs i.e. cycle error log - job start time
$dailymaintenanceschedule = $jobprefix + ' - Daily Maintenance'

 New-DbaAgentSchedule -SqlInstance $sqlinstance -Schedule $dailymaintenanceschedule -FrequencyType Daily -FrequencyInterval 1 -StartTime $dailymaintenancestarttime -Force


### Please confirm that you are running the most recent version of dbatools

2.1.16

### Other details or mentions

_No response_

### What PowerShell host was used when producing this error

Windows PowerShell ISE (powershell_ise.exe)

### PowerShell Host Version


Name                           Value                                                                                                                                                                                                                             
----                           -----                                                                                                                                                                                                                             
PSVersion                      5.1.22621.2506                                                                                                                                                                                                                    
PSEdition                      Desktop                                                                                                                                                                                                                           
PSCompatibleVersions           {1.0, 2.0, 3.0, 4.0...}                                                                                                                                                                                                           
BuildVersion                   10.0.22621.2506                                                                                                                                                                                                                   
CLRVersion                     4.0.30319.42000                                                                                                                                                                                                                   
WSManStackVersion              3.0                                                                                                                                                                                                                               
PSRemotingProtocolVersion      2.3                                                                                                                                                                                                                               
SerializationVersion           1.1.0.1                                                                                                                                                                                                                           




### SQL Server Edition and Build number

Microsoft SQL Server 2022 (RTM-GDR) (KB5035432) - 16.0.1115.1 (X64)   Mar 15 2024 01:13:46   Copyright (C) 2022 Microsoft Corporation  Developer Edition (64-bit) on Windows 10 Pro 10.0 <X64> (Build 22631: ) 

### .NET Framework Version

.NET Framework 4.8.9241.0

### PR DESCRIPTION
**Pull request by andreasjordan**
## Type of Change

 - [x] Bug fix (non-breaking change, fixes #9388 )
 - [ ] New feature (non-breaking change, adds functionality, fixes # )
 - [ ] Breaking change (affects multiple commands or functionality, fixes # )
 - [ ] Ran manual Pester test and has passed (`.\tests\manual.pester.ps1`)
 - [ ] Adding code coverage to existing functionality
 - [ ] Pester test is included
 - [ ] If new file reference added for test, has is been added to github.com/dataplat/appveyor-lab ?
 - [ ] Unit test is included
 - [ ] Documentation
 - [ ] Build system

See issue for details.

We now use the correct types for the SMO properties.

Maybe we should also add two new parameters StartDateTime and EndDateTime with [datetime] datatype as an alternative for the four string parameters. I can do this if other contributors agree.

### CODE REVIEW

**Comment by andreasjordan** [comment]
I don't see why the test fails. The test uses Schedules, but I don't see a relation to the code change. Can someone help?

**Comment by potatoqualitee** [comment]
i wondered if these were breaking changes. ill take a closer look this weekend 👍🏼

**Comment by andreasjordan** [comment]
Just found a copy-paste-bug I introduced. Will fix in a minute...

**Comment by andreasjordan** [comment]
Now all tests pass.

**Comment by potatoqualitee** [comment]
excellent, thanks andreas!

**Pull request merged**
