### PR TITLE
Get-DbaDbFile: add Database ID

### LINKED ISSUE #8053: Get-DbaDbFile add Database ID
### Summarize Functionality

The true identifier of a database is it's ID.
Since a DB can be renamed, there can be mismatches in historical data.

Just adding the DB_ID() to the output columns in the query + adding it to the PS obj properties should do it.

### Is there a command that is similiar or close to what you are looking for?

No

### Technical Details

_No response_

### PR DESCRIPTION
**Pull request by lancasteradam**
## Type of Change

 - [ ] Bug fix (non-breaking change, fixes # )
 - [x] New feature (non-breaking change, adds functionality, fixes #8053 )
 - [ ] Breaking change (effects multiple commands or functionality, fixes # )
 - [x] Ran manual Pester test and has passed (`.\tests\manual.pester.ps1`)
 - [x] Adding code coverage to existing functionality
 - [x] Pester test is included
 - [ ] If new file reference added for test, has is been added to github.com/dataplat/appveyor-lab ?
 - [ ] Unit test is included
 - [ ] Documentation
 - [ ] Build system

### Purpose

Minor change to add Database ID to the output as requested in #8053 

### Approach

The database object is available at the end of the command so the ID is added into the return object.

### Commands to test

New Pester tests are added to confirm that the database ID is returned.

### CODE REVIEW

**Review by andreasjordan — APPROVED** [review]
Changes look good. But should we add the DatabaseID to the output of other commands as well?

**Comment by lancasteradam** [comment]
@andreasjordan, that is a great idea. I would suggest that be a separate PR or a series of PRs. I added an issue #8183 for the analysis to be done.

**Comment by potatoqualitee** [comment]
awesome, thank you both 🥳

**Comment by PowerDBAKlaas** [comment]
Thanks @andreasjordan @lancasteradam !!

**Pull request merged**
