### PR TITLE
Install-DbaInstance - Fix for installing MachineLearning in SQL Server 2022

### LINKED ISSUE #9149: Install-DbaInstance -Feature MachineLearning fails for SQL Server 2022
### Verified issue does not already exist?

I have searched and found no existing issue

### What error did you receive?

When running Install-DbaInstance -Version 2022 -Feature Engine,FullText,MachineLearning,IntegrationServices it errors out and fails do to the MachineLearning option. The Error states 'SQL_INST_MR' is not a valid value for settings 'FEATURES'.

My understanding is that when using the MachineLearning Feature with Install-DbaInstance this enables AdvancedAnalytics, SQL_INST_MR, SQL_INST_MPY in the config options, however with SQL Server 2022 you only use AdvancedAnalytics for the machine learning feature and SQL_INST_MR, SQL_INST_MPY are no longer used

### Steps to Reproduce

```powershell
Import-Module -Name dbatools

$config = @{
    UPDATEENABLED = "True"
    UPDATESOURCE = "MU"
    BROWSERSVCSTARTUPTYPE = "Disabled"
    USESQLRECOMMENDEDMEMORYLIMITS = "True"
}

$installParams = @{
    Version             = "2022"
    Feature             = 'Engine','FullText','MachineLearning','IntegrationServices'
    PerformVolumeMaintenanceTasks = $true
    SqlCollation        = 'SQL_Latin1_General_CP1_CI_AS'
    AuthenticationMode  = "Windows"
    InstancePath        = "E:\Data"
    DataPath            = "E:\Data\MSSQL16.MSSQLSERVER\MSSQL\Data"
    LogPath             = "F:\Log\MSSQL16.MSSQLSERVER\MSSQL\Data"
    TempPath            = "G:\TempDB\MSSQL16.MSSQLSERVER\MSSQL\Data"
    BackupPath          = "H:\SQL_Backups\MSSQLSERVER"
    AdminAccount        = "LAB\SQL_Admins"
    Path                = "C:\SQL2022"
    Restart             = $true
    Verbose             = $true
    Confirm             = $false
    Configuration       = $config
}

Install-DbaInstance @installParams
```

### Please confirm that you are running the most recent version of dbatools

```
Major  Minor  Build  Revision
-----  -----  -----  --------
2      1      4      -1     
```

### Other details or mentions

In order to work around this issue I listed the features in the $config variable instead of as one of the cmdlet Feature parameters

$config = @{
    FEATURES = "SQLENGINE, FULLTEXT, ADVANCEDANALYTICS, IS"
    UPDATEENABLED = "True"
    UPDATESOURCE = "MU"
    BROWSERSVCSTARTUPTYPE = "Disabled"
    USESQLRECOMMENDEDMEMORYLIMITS = "True"
}

$installParams = @{
    Version             = "2022"
    PerformVolumeMaintenanceTasks = $true
    SqlCollation        = 'SQL_Latin1_General_CP1_CI_AS'
    AuthenticationMode  = "Windows"
    InstancePath        = "E:\Data"
    DataPath            = "E:\Data\MSSQL16.MSSQLSERVER\MSSQL\Data"
    LogPath             = "F:\Log\MSSQL16.MSSQLSERVER\MSSQL\Data"
    TempPath            = "G:\TempDB\MSSQL16.MSSQLSERVER\MSSQL\Data"
    BackupPath          = "H:\SQL_Backups\MSSQLSERVER"
    AdminAccount        = "DESKTOP-9L6BV1G\SQL_Admins"
    Path                = "C:\SQL2022"
    Restart             = $true
    Verbose             = $true
    Confirm             = $false
    Configuration       = $config
}

Install-DbaInstance @installParams

### What PowerShell host was used when producing this error

Windows PowerShell ISE (powershell_ise.exe)

### PowerShell Host Version

Powershell 5.1

### SQL Server Edition and Build number

SQL Server 2022 Developper Edition

### .NET Framework Version

.NET Framework 4.8.9195.0

### PR DESCRIPTION
**Pull request by andreasjordan**
## Type of Change

 - [x] Bug fix (non-breaking change, fixes #9149 )
 - [ ] New feature (non-breaking change, adds functionality, fixes # )
 - [ ] Breaking change (affects multiple commands or functionality, fixes # )
 - [ ] Ran manual Pester test and has passed (`.\tests\manual.pester.ps1`)
 - [ ] Adding code coverage to existing functionality
 - [ ] Pester test is included
 - [ ] If new file reference added for test, has is been added to github.com/dataplat/appveyor-lab ?
 - [ ] Unit test is included
 - [ ] Documentation
 - [ ] Build system

See issue for details.

### CODE REVIEW

**Comment by andreasjordan** [comment]
I just wanted to add two lines to the json file - I have no idea why this is now a complete new file. I have documented the changes in the issue - maby someone else can open a pull request for that.

**Comment by potatoqualitee** [comment]
@andreasjordan seems like the encoding may have changed?

**Comment by andreasjordan** [comment]
But the diff only shows adding a new file and not deleting an old file. Very strange. Will remove my local repo and get a new clone...

**Comment by andreasjordan** [comment]
Recloning did not help, giving up.

**Pull request closed without merging**
