### PR TITLE
Set-DbaDbCompatability - breaking change, code cleanup, add integration testing

### PR DESCRIPTION
**Pull request by wsmelton**
## Please read -- recent changes to our repo
On November 10, 2022, [we removed some bloat from our repository (for the second and final time)](https://github.com/dataplat/dbatools/issues/8542). This change requires that all contributors reclone or refork their repo.

PRs from repos that have not been recently reforked or recloned will be closed and @potatoqualitee will cherry-pick your commits and open a new PR with your changes.

 - [x] Please confirm you have the smaller repo (85MB .git directory vs 275MB or 110MB or 185MB .git directory)

## Type of Change

 - [ ] Bug fix (non-breaking change, fixes # )
 - [ ] New feature (non-breaking change, adds functionality, fixes # )
 - [x] Breaking change (effects multiple commands or functionality, ref #8718 )
 - [ ] Ran manual Pester test and has passed (`.\tests\manual.pester.ps1`)
 - [x] Adding code coverage to existing functionality
 - [x] Pester test is included
 - [ ] If new file reference added for test, has is been added to github.com/dataplat/appveyor-lab ?
 - [ ] Unit test is included
 - [ ] Documentation
 - [ ] Build system

### Purpose
Reference ticket #8718 remove the deprecated parameter that requires us to continue to maintain this command with SQL Server releases. Removing this as breaking change as part of 2.0.

### Approach
- Remove deprecated parameter `TargetCompatibility`
- Adjust code for removal of that parameter
- Adjust verbose output
- Add integration testing (based on verbose output)

### Screenshots

image

image

### CODE REVIEW

**Comment by potatoqualitee** [comment]
ahhh! i need to update that gh action to recognize the source branch, k

**Comment by wsmelton** [comment]
@potatoqualitee pushed PR to your action to handle the branch name pattern potatoqualitee/azautomodule#4

**Comment by potatoqualitee** [comment]
Oh@ oops! thank you, shawn. i didnt see the notifications because i have like 1000. i ended up just removing the /, lemme go look.

**Comment by potatoqualitee** [comment]
Failing with "could not obtain exclusive lock on model" 🤔

**Comment by wsmelton** [comment]
That looks like the instances in Appveyor are unstable. Could it be we have to much running in that group now? (Work is blocking me from checking that log artifact 😟)

**Comment by potatoqualitee** [comment]
its such a weird error but even weirder, it did it for both instance2 and instance3??

**Comment by potatoqualitee** [comment]
hey shawn, i got it working by killing all connections to model but one still failed. i ended up disabling one of the tests because it said it expected no output but then it checked for 1 output. the output, however, was null. please take a look.

**Comment by wsmelton** [comment]
The command will not output anything if no compatibility change is found for the database. So it test against a database that should have matched the instance level.

If the type is returning it means it is finding something not expected in that instance. I'll take a look but didn't have this problem on a local machine and server.

**Comment by potatoqualitee** [comment]
ugh, i need to pin the version of the library, maybe. the new one was causing issues so i merged my library branch into this one. sorry, it's gonna be a little bit of a mess while i try to get this sorted.

**Comment by potatoqualitee** [comment]
ayyy we got the green

**Comment by potatoqualitee** [comment]
Since this seems like a test or appveyor issue, I'll merge it and then please submit a new PR to address the test 👍🏼

**Comment by PeterMBQ** [comment]
Hi! I have a question regarding the issue - do you maybe have an idea already when it can be resolved?

**Comment by PeterMBQ** [comment]
> Hi! I have a question regarding the issue - do you maybe have an idea already when it will be resolved?

We would be interested in testing the alfa/beta solution, If it would be okay for you to share the latest version of dbtools we are eager to test it on our environments.

**Comment by potatoqualitee** [comment]
hello peter, please run

`Install-Module dbatools -AllowPrerelease` and you should be set!

**Pull request merged**
