### PR TITLE
Find-DbaInstance - Add SqlInstance to default output

### LINKED ISSUE #8187: Find-DbaInstance - Add SqlInstance to default output
### Summarize Functionality

Add SqlInstance to default output.

### Is there a command that is similiar or close to what you are looking for?

No

### Technical Details

_No response_

### PR DESCRIPTION
**Pull request by andreasjordan**
## Type of Change

 - [ ] Bug fix (non-breaking change, fixes # )
 - [x] New feature (non-breaking change, adds functionality, fixes #8187 )
 - [ ] Breaking change (effects multiple commands or functionality, fixes # )
 - [ ] Ran manual Pester test and has passed (`.\tests\manual.pester.ps1`)
 - [ ] Adding code coverage to existing functionality
 - [ ] Pester test is included
 - [ ] If new file reference added for test, has is been added to github.com/dataplat/appveyor-lab ?
 - [ ] Unit test is included
 - [ ] Documentation
 - [ ] Build system

As most of the commands output ComputerName, InstanceName and SqlInstance as the first three properties, Find-DbaInstance should do that as well.

image

### CODE REVIEW

**Comment by potatoqualitee** [comment]
Very nice! I'd like this too.

**Comment by potatoqualitee** [comment]
So we had left this off intentionally because it may be misleading if there's incomplete information (due to permissions/access). I wonder if we can null it out in that event.

**Comment by andreasjordan** [comment]
This is the code:
https://github.com/dataplat/dbatools/blob/57e3715bf351448a1ecd683085d74c637e03aea6/bin/projects/dbatools/dbatools/Discovery/DbaInstanceReport.cs#L48-L63

So it is always build from ComputerName and InstanceName (and sometimes Port). Should never be null.

**Comment by potatoqualitee** [comment]
@jpomfret and i are wondering if there is a combination where we can see we have a server with default + named instance  but can't get instance name... so results will end up listing two results both with just the servername as SqlInstance?

**Comment by potatoqualitee** [comment]
if so, do we just add a warning to the docs that the sqlinstance name is best guess?

**Pull request merged**
