### PR TITLE
Get-DbaDbBackupHistory: Add DatabaseId to the return object

### PR DESCRIPTION
**Pull request by lancasteradam**
- [x] Please confirm you have the smaller repo (110MB .git directory vs 275MB .git directory)

## Type of Change

 - [ ] Bug fix (non-breaking change, fixes # )
 - [x] New feature (non-breaking change, adds functionality, relates to #8183  )
 - [ ] Breaking change (effects multiple commands or functionality, fixes # )
 - [x] Ran manual Pester test and has passed (`.\tests\manual.pester.ps1`)
 - [ ] Adding code coverage to existing functionality
 - [ ] Pester test is included
 - [ ] If new file reference added for test, has is been added to github.com/dataplat/appveyor-lab ?
 - [ ] Unit test is included
 - [ ] Documentation
 - [ ] Build system

### Purpose

Minor change to add DatabaseId to the return object.

### Approach

Pull the database ID from sys.databases based on the db name that is in the backup.

### Commands to test

Minor update to the existing pester tests.

### CODE REVIEW

**Comment by potatoqualitee** [comment]
Thank you, Adam! I will do the compile -- please remove the binaries and I will merge 👍🏼

**Comment by Griffin641498** [comment]
> * [x]  Please confirm you have the smaller repo (110MB .git directory vs 275MB .git directory)
> 
> ## Type of Change
> * [ ]  Bug fix (non-breaking change, fixes # )
> * [x]  New feature (non-breaking change, adds functionality, relates to [Add DatabaseID to the return object for relevant commands #8183](https://github.com/dataplat/dbatools/issues/8183)  )
> * [ ]  Breaking change (effects multiple commands or functionality, fixes # )
> * [x]  Ran manual Pester test and has passed (`.\tests\manual.pester.ps1`)
> * [ ]  Adding code coverage to existing functionality
> * [ ]  Pester test is included
> * [ ]  If new file reference added for test, has is been added to github.com/dataplat/appveyor-lab ?
> * [ ]  Unit test is included
> * [ ]  Documentation
> * [ ]  Build system
> 
> ### Purpose
> Minor change to add DatabaseId to the return object.
> 
> ### Approach
> Pull the database ID from sys.databases based on the db name that is in the backup.
> 
> ### Commands to test
> Minor update to the existing pester tests.

**Comment by potatoqualitee** [comment]
Thank you! I have another library change too, if you can imagine! I'll merge that one in and then compile and release today 🤩

**Comment by potatoqualitee** [comment]
Unfortunately, you still have an old copy of the repo with the bigger library somehow. I'll close this PR and make a new one with the smaller repo with your changes.

image

**Pull request closed without merging**
