### PR TITLE
Update dbatools-buildref-index.json SQL2022 CU15

### PR DESCRIPTION
**Pull request by MikeyBronowski**
## Type of Change

 - [ ] Bug fix (non-breaking change, fixes # )
 - [ ] New feature (non-breaking change, adds functionality, fixes # )
 - [ ] Breaking change (affects multiple commands or functionality, fixes # )
 - [ ] Ran manual Pester test and has passed (`.\tests\manual.pester.ps1`)
 - [ ] Adding code coverage to existing functionality
 - [ ] Pester test is included
 - [ ] If new file reference added for test, has is been added to github.com/dataplat/appveyor-lab ?
 - [ ] Unit test is included
 - [x] Documentation
 - [ ] Build system

### Purpose

[KB5041321 - Cumulative Update 15 for SQL Server 2022](https://learn.microsoft.com/en-us/troubleshoot/sql/releases/sqlserver-2022/cumulativeupdate15)

### CODE REVIEW

**Comment by MikeyBronowski** [comment]
Lol, time zones :) 

`Describe : Get-DbaBuild Unit Test
Context  : Validate LastUpdated property
Name     : It LastUpdated is not in the future
Result   : Failed
Message  : Expected the actual value to be less than 2024-09-25T23:22:51.2771146+00:00, but got 2024-09-26T00:00:00.0000000.
`

**Review by niphlod — APPROVED** [review]

**Comment by niphlod** [comment]
@potatoqualitee can you merge this ? the community is always eager to get updates ASAP. given we linked the public data to the file present in development, at least that step needs to happen, a full release of the module is not needed.

**Comment by niphlod** [comment]
BTW @potatoqualitee I think we need to re-view the update process (https://github.com/dataplat/dataplat.github.io/blob/master/.github/workflows/updateassets.yml) as waiting for a PR to be merged in in the last few months is resulting in several days of "staleness" on the index

**Comment by wsmelton** [comment]
We can likely get a workflow created to auto merge these

**Pull request merged**
