### PR TITLE
Export-DbaUser - Refactor T-SQL User-Role Scripting to Eliminate Dependencies

### LINKED ISSUE #9231: Export-DbaUser includes unrelated database roles in export
### Verified issue does not already exist?

I have searched and found no existing issue

### What error did you receive?

No errors. Just wrong results.

### Steps to Reproduce

1. Execute the following T-SQL commands to set up the database, user, and roles:
```
USE master;
GO
CREATE DATABASE db1;
GO
CREATE LOGIN user1 WITH PASSWORD = 'StrongPassword!123';
GO
USE db1;
GO
CREATE USER user1 FOR LOGIN user1;
GO
CREATE ROLE role1;
CREATE ROLE role2;
GO
EXEC sp_addrolemember 'role1', 'user1';
GO
```
2. Export the user using dbatools' `Export-DbaUser` command:
```
Export-DbaUser -SqlInstance node1 -Database db1 -User user1
```
## Expected Behavior
The export should only include the user `user1` and any roles or permissions directly associated with `user1`.

## Actual Behavior
The export includes the creation of `role2`, which has no association with the user `user1`. Here is the exported script:
```
USE [db1]
GO
IF NOT EXISTS (SELECT * FROM sys.database_principals WHERE name = N'role1' AND type = 'R')
CREATE ROLE [role1]
GO
IF NOT EXISTS (SELECT * FROM sys.database_principals WHERE name = N'role2' AND type = 'R')
CREATE ROLE [role2]
GO
IF NOT EXISTS (SELECT * FROM sys.database_principals WHERE name = N'user1')
CREATE USER [user1] FOR LOGIN [user1] WITH DEFAULT_SCHEMA=[dbo]
GO
ALTER ROLE [role1] ADD MEMBER [user1]
GO
GRANT CONNECT TO [user1] AS [dbo];
GO
```

This issue can lead to unnecessary bloat in the exported script and potentially create security misconfigurations if the script is run without review in different environments. It would be beneficial if `Export-DbaUser` could improve the logic to limit the export to entities that are explicitly related to the specified user.

### Please confirm that you are running the most recent version of dbatools

```

Major  Minor  Build  Revision
-----  -----  -----  --------
2      1      7      -1      

```

### Other details or mentions

_No response_

### What PowerShell host was used when producing this error

Windows PowerShell (powershell.exe)

### PowerShell Host Version

```

Name                           Value                                                                                   
----                           -----                                                                                   
PSVersion                      5.1.20348.2110                                                                          
PSEdition                      Desktop                                                                                 
PSCompatibleVersions           {1.0, 2.0, 3.0, 4.0...}                                                                 
BuildVersion                   10.0.20348.2110                                                                         
CLRVersion                     4.0.30319.42000                                                                         
WSManStackVersion              3.0                                                                                     
PSRemotingProtocolVersion      2.3                                                                                     
SerializationVersion           1.1.0.1                                                                                 

```

### SQL Server Edition and Build number

```
Microsoft SQL Server 2016 (SP3) (KB5003279) - 13.0.6300.2 (X64)   Aug  7 2021 01:20:37   Copyright (c) Microsoft Corporation  Enterprise Edition: Core-based Licensing (64-bit) on Windows Server 2022 Datacenter 10.0 <X64> (Build 20348: ) (Hypervisor) 
```

### .NET Framework Version

```
PSChildName                      Version
-----------                      -------
v2.0.50727                       2.0.50727.4927
v3.0                             3.0.30729.4926
Windows Communication Foundation 3.0.4506.4926
Windows Presentation Foundation  3.0.6920.4902
v3.5                             3.5.30729.4926
Client                           4.8.04161
Full                             4.8.04161
Client                           4.0.0.0
```

### PR DESCRIPTION
**Pull request by 0x7FFFFFFFFFFFFFFF**
Refactored the T-SQL scripting for user-role assignments to enforce independence between scripts. This change removes the need to track which roles have been scripted, preventing dependency issues when scripts are run out of order. Below is a detailed introduction to the issue and the solution.

In this new approach of scripting, we do not maintain a variable to track the roles that have been scripted. Our method involves a consistent verification process for each user against the complete list of roles. This ensures that we dynamically include only the roles to which a user belongs. For example, consider two users: user1 is associated with role1 and role2, while user2 is associated with role1 and role3.

Attempting to memorize the scripted roles could result in Transact-SQL (T-SQL) statements such as:

```
IF NOT EXISTS (role1)
  CREATE ROLE role1
IF NOT EXISTS (role2)
  CREATE ROLE role2
IF NOT EXISTS (user1)
  CREATE USER user1
ADD user1 TO role1
ADD user1 TO role2

-- And for another user:

IF NOT EXISTS (role3)
  CREATE ROLE role3
IF NOT EXISTS (user2)
  CREATE USER user2
ADD user2 TO role1
ADD user2 TO role3
```
`

However, this script inadvertently introduces a dependency issue. To ensure user2 is properly configured, the script segment for user1 must be executed first due to the shared role1. To circumvent this issue and remove interdependencies, we opt to match each user against all potential roles. Consequently, roles are scripted per user membership, resulting in T-SQL like:

```
IF NOT EXISTS (role1)
  CREATE ROLE role1
IF NOT EXISTS (role2)
  CREATE ROLE role2
IF NOT EXISTS (user1)
  CREATE USER user1
ADD user1 TO role1
ADD user1 TO role2

-- And for another user:

IF NOT EXISTS (role1)
  CREATE ROLE role1
IF NOT EXISTS (role3)
  CREATE ROLE role3
IF NOT EXISTS (user2)
  CREATE USER user2
ADD user2 TO role1
ADD user2 TO role3
```

While this method may produce some redundant code (e.g., checking and creating role1 twice), it guarantees that each portion of the script is self-sufficient and can be executed independently of others. Therefore, users can selectively execute any segment of the script without concern for execution order or dependencies.

## Please read -- recent changes to our repo
On November 10, 2022, [we removed some bloat from our repository (for the second and final time)](https://github.com/dataplat/dbatools/issues/8542). This change requires that all contributors reclone or refork their repo.

PRs from repos that have not been recently reforked or recloned will be closed and @potatoqualitee will cherry-pick your commits and open a new PR with your changes.

 - [x] Please confirm you have the smaller repo (85MB .git directory vs 275MB or 110MB or 185MB .git directory)

## Type of Change

 - [x] Bug fix (non-breaking change, fixes #9231 )
 - [ ] New feature (non-breaking change, adds functionality, fixes # )
 - [ ] Breaking change (affects multiple commands or functionality, fixes # )
 - [ ] Ran manual Pester test and has passed (`.\tests\manual.pester.ps1`)
 - [ ] Adding code coverage to existing functionality
 - [ ] Pester test is included
 - [ ] If new file reference added for test, has is been added to github.com/dataplat/appveyor-lab ?
 - [ ] Unit test is included
 - [ ] Documentation
 - [ ] Build system

### CODE REVIEW

**Comment by niphlod** [comment]
hum, the single exported file before had issues ? 
if not, is this just a reorder of the statements (and an enlargement if counting lines and statements) to make sure that you can execute not only the exported files, but also pieces of them ?

**Comment by 0x7FFFFFFFFFFFFFFF** [comment]
> hum, the single exported file before had issues ? if not, is this just a reorder of the statements (and an enlargement if counting lines and statements) to make sure that you can execute not only the exported files, but also pieces of them ?

The issue with the single exported file including roles not pertinent to the user. The pull request has made two justments:

1. Exclude any roles that are unrelated to the user.
2. It now generates all the roles a user is a member of within their individual script. This means that for each user, the generated script will include the necessary statements to create roles, create the user, and add the user to their respective roles. This negates the need to reference role creation statements from other users' scripts, as each user's script is self-contained and fully executable on its own.

**Comment by niphlod** [comment]
okay, then maybe it's good to put a regression test into tests/Export-DbaUser.Tests.ps1 to avoid this "way" getting reverted by a next edit.

**Comment by 0x7FFFFFFFFFFFFFFF** [comment]
> * Exclude any roles that are unrelated to the user.
> * It now generates all the roles a user is a member of within their individual script. This means that for each user, the generated script will include the necessary statements to create roles, create the user, and add the user to their respective roles. This negates the need to reference role creation statements from other users' scripts, as each user's script is self-contained and fully executable on its own.

Can we change it like this:

1. Exclude any roles that are unrelated to the user. So that the exported script is more clean and relevant.
2. Maybe we can add a switch parameter, something like -NoRoleDependency. When the user specified this parameter, we export in a no dependency way (so that there will be some duplicate CREATE ROLE statements). If not, keep current logic.

**Comment by potatoqualitee** [comment]
Thank you all for y our feedback. I will merge once the PR is approved.

**Comment by potatoqualitee** [comment]
Any updates?

**Comment by potatoqualitee** [comment]
@niphlod @wsmelton can i merge? I do not have an opinion on this particular topic other than it seems useful.

Oh but also, if the work is already done in T-SQL then we don't need it to move to PS? That'd be more of a preference than a requiement.

**Comment by niphlod** [comment]
I don't have any preference in the matter of "PS vs T-SQL" but I'd add a regr test to make sure this behaviour doesn't get reverted at a later stage.

**Comment by potatoqualitee** [comment]
Thank you -- @0x7FFFFFFFFFFFFFFF is that something you can do? add in a test that would fail if your PR's functionality gets impacted?

**Comment by 0x7FFFFFFFFFFFFFFF** [comment]
Thanks for reviewing the pull request and for the suggestions. I'm pretty busy recently, which has impacted my ability to respond promptly. I appreciate your understanding and patience.

Regarding the test for the `Export-DbaUser` refactoring, I must admit that I am not very familiar with it. I'll give it a try and will reach out if I need specific guidance or feedback.

**Comment by niphlod** [comment]
we can definitely help, just need to prop up two user with roles exposing the behaviour you want to fix and then make sure everything stays in the same way "forever" ;-)

**Comment by 0x7FFFFFFFFFFFFFFF** [comment]
I've added a test.

**Comment by potatoqualitee** [comment]
Thank you very much! Apologies for the delay. Merging finally 🙏🏼

**Pull request merged**
