### PR TITLE
Get-DbaDbBackupHistory - Add parameter LsnSort

### PR DESCRIPTION
**Pull request by andreasjordan**
Just a draft at the moment. 

As this is a very complex command more people should have a look at this.

It might help to solve #5399 - but maybe not.

### CODE REVIEW

**Comment by potatoqualitee** [comment]
ahh thank you, ,didnt realize it'd be complex. godspeed 😅

**Comment by potatoqualitee** [comment]
I like the approach, @niphlod or @jpomfret what do you think?

**Comment by jpomfret** [comment]
I think it makes sense to me, presuming that `$LsnSort = "LastLsn"` would replicate the current behaviour of the command.

**Comment by andreasjordan** [comment]
Yes, the default is the current behaviour - so no breaking change.

Only in combination with `Get-DbaAgBackupHistory` things change a bit, as there is a default of "FirstLsn" which will then be handed to `Get-DbaDbBackupHistory`.

**Comment by potatoqualitee** [comment]
hey @andreasjordan -- i think this gets an overall approval. Can you fix the conflict and set it ready to PR? I'm about to do some massive changes and need all PRs to be merged.

**Comment by potatoqualitee** [comment]
ill resolve this conflict, brb

**Comment by potatoqualitee** [comment]
awww yeahhh

**Pull request merged**
