### PR TITLE
Copy-DbaDbQueryStoreOption: Add DatabaseID to the result set

### PR DESCRIPTION
**Pull request by lancasteradam**
## Type of Change

 - [ ] Bug fix (non-breaking change, fixes # )
 - [x] New feature (non-breaking change, adds functionality, relates to #8183 )
 - [ ] Breaking change (effects multiple commands or functionality, fixes # )
 - [x] Ran manual Pester test and has passed (`.\tests\manual.pester.ps1`)
 - [x] Adding code coverage to existing functionality
 - [x] Pester test is included
 - [ ] If new file reference added for test, has is been added to github.com/dataplat/appveyor-lab ?
 - [ ] Unit test is included
 - [ ] Documentation
 - [ ] Build system

### Purpose

Adding the SourceDatabaseID and DestinationDatabaseID as discussed in #8183 

### Approach

Minor refactoring along with the new output columns.

### Commands to test

See the new pester tests.

### CODE REVIEW

**Comment by potatoqualitee** [comment]
Thank you, @lancasteradam ! There must be some prompt waiting for input -- the test keeps timing out, waiting over an hour for results from Copy-DbaDbQueryStoreOption.

**Comment by lancasteradam** [comment]
Thanks @potatoqualitee, I changed the tests to use instance2 since Query Store was introduced in SQL 2016. It seems to be ok now, but there was an error from Find-DbaAgentJob.Tests.ps1 that seems to be unrelated.

**Comment by lancasteradam** [comment]
Fixed an additional issue in the pester test as noted in the commit comment above.

**Comment by potatoqualitee** [comment]
Thanks so much 💯 !

**Pull request merged**
