### PR TITLE
Refactored function to improve code clarity and fix issue #8807

### LINKED ISSUE #8807: Move-DbaDbFile shows incorrect SourceFileDeleted status when -DeleteAfterMove flag is ommited
### Verified issue does not already exist?

I have searched and found no existing issue

### What error did you receive?

When Move-DbaDbFile is used without -DeleteAfterMove flag it always shows 
SourceFileDeleted    : True
Which is incorrect

Please see steps to reproduce for an example command used and output

### Command

```powershell
 Move-DbaDbFile -SqlInstance localhost -Database playground -FileType Both -FileDestination D:\databases\subfolder
```

### Output

Instance             : localhost
Database             : playground
LogicalName          : playground
Source               : D:\databases\playground.mdf
Destination          : D:\databases\subfolder\playground.mdf
Result               : Success
DatabaseFileMetadata : Updated
SourceFileDeleted    : True

Instance             : localhost
Database             : playground
LogicalName          : playground_log
Source               : D:\databases\playground_log.ldf
Destination          : D:\databases\subfolder\playground_log.ldf
Result               : Success
DatabaseFileMetadata : Updated
SourceFileDeleted    : True

### Original files still there

PS C:\WINDOWS\system32> ls D:\databases\pla*

Directory: D:\databases

Mode                 LastWriteTime         Length Name                                                                                                                                                                                  
----                 -------------         ------ ----                                                                                                                                                                                  
-a----         3/12/2023   7:04 PM    34084618240 playground.mdf                                                                                                                                                                        
-a----         3/12/2023   7:04 PM    40592474112 playground_log.ldf                                                                                                                                                                    

PS C:\WINDOWS\system32> ls D:\databases\subfolder\pla*

Directory: D:\databases\subfolder

Mode                 LastWriteTime         Length Name                                                                                                                                                                                  
----                 -------------         ------ ----                                                                                                                                                                                  
-a----         3/12/2023   7:10 PM    34084618240 playground.mdf                                                                                                                                                                        
-a----         3/12/2023   7:10 PM    40592474112 playground_log.ldf

### Please confirm that you are running the most recent version of dbatools

1.1.145

### Other details or mentions

_No response_

### What PowerShell host was used when producing this error

Windows PowerShell ISE (powershell_ise.exe)

### PowerShell Host Version

Name                           Value                                                                                                                                                                                                    
----                           -----                                                                                                                                                                                                    
PSVersion                      5.1.19041.2364                                                                                                                                                                                           
PSEdition                      Desktop                                                                                                                                                                                                  
PSCompatibleVersions           {1.0, 2.0, 3.0, 4.0...}                                                                                                                                                                                  
BuildVersion                   10.0.19041.2364                                                                                                                                                                                          
CLRVersion                     4.0.30319.42000                                                                                                                                                                                          
WSManStackVersion              3.0                                                                                                                                                                                                      
PSRemotingProtocolVersion      2.3                                                                                                                                                                                                      
SerializationVersion           1.1.0.1                                                                                                                                                                                                  

### SQL Server Edition and Build number

Microsoft SQL Server 2019 (RTM-CU16-GDR) (KB5014353) - 15.0.4236.7 (X64)   May 29 2022 15:55:47   Copyright (C) 2019 Microsoft Corporation  Developer Edition (64-bit) on Windows 10 Pro 10.0 <X64> (Build 19045: ) 

The SQL Server version should not matter

### .NET Framework Version

PSChildName                      Version       
-----------                      -------       
v2.0.50727                       2.0.50727.4927
v3.0                             3.0.30729.4926
Windows Communication Foundation 3.0.4506.4926 
Windows Presentation Foundation  3.0.6920.4902 
v3.5                             3.5.30729.4926
Client                           4.8.04084     
Full                             4.8.04084     
Client                           4.0.0.0

### PR DESCRIPTION
**Pull request by HCRitter**
This commit refactors the function to initialize the return object once and remove code clutter, resulting in improved code clarity. Additionally, several properties have been changed to ensure correct responses are returned, fixing issue #8807.

## Please read -- recent changes to our repo
On November 10, 2022, [we removed some bloat from our repository (for the second and final time)](https://github.com/dataplat/dbatools/issues/8542). This change requires that all contributors reclone or refork their repo.

PRs from repos that have not been recently reforked or recloned will be closed and @potatoqualitee will cherry-pick your commits and open a new PR with your changes.

 - [x] Please confirm you have the smaller repo (85MB .git directory vs 275MB or 110MB or 185MB .git directory)

## Type of Change

 - [X] Bug fix (non-breaking change, fixes #8807 )
 - [ ] New feature (non-breaking change, adds functionality, fixes # )
 - [ ] Breaking change (affects multiple commands or functionality, fixes # )
 - [ ] Ran manual Pester test and has passed (`.\tests\manual.pester.ps1`)
 - [ ] Adding code coverage to existing functionality
 - [ ] Pester test is included
 - [ ] If new file reference added for test, has is been added to github.com/dataplat/appveyor-lab ?
 - [ ] Unit test is included
 - [] Documentation
 - [ ] Build system

### Purpose
found the solution to a minor code issue that showed the wrong custom-object return properties

### Approach

This commit refactors the function to initialize the return object once and remove code clutter, resulting in improved code clarity. Additionally, several properties have been changed to ensure correct responses are returned, fixing issue #8807.

### CODE REVIEW

**Comment by potatoqualitee** [comment]
Awesome, thank you so much, @HCRitter! @ClaudioESSilva any chance you got some time to review?

**Comment by andreasjordan** [comment]
The dbatools style test is failing. @HCRitter please use Invoke-DbatoolsFormatter to correct the formatting.

**Comment by potatoqualitee** [comment]
Thank you, @andreasjordan  -- I'll fix it real quick 👍🏼

**Comment by HCRitter** [comment]
thank you, @potatoqualitee I was doing that as well, just to understand the whole process for contributing. Fun fact: it changed bits that were originally in the code before my changes :D

**Comment by potatoqualitee** [comment]
Thank you for your PR, it will be published with 2.0.1 today 😊

**Pull request merged**
