### PR TITLE
Bug Fix #9068. New-DbaDbUser

### LINKED ISSUE #9068: New-dbaDBUser does not add user to databases if the -Database parameter is ommitted
### Verified issue does not already exist?

I have searched and found no existing issue

### What error did you receive?

No errors are returned.  The function completes without errors or output; user is not added to any databases.  If a database is explicitly specified using -Database, the function works as expected.

### Steps to Reproduce

$reqLogin = 'TestLogin'
$conn = connect-dbainstance -sqlinstance MySQLServer -trustservercertificate

#### This fails
new-dbadbuser -sqlinstance $conn -login $reqLogin -username $reqLogin -Confirm:$false -ErrorAction Stop

#### This works
new-dbadbuser -sqlinstance $conn -login $reqLogin -username $reqLogin -Confirm:$false -ErrorAction Stop -Database mydb1, mydb2, mydb3

### Please confirm that you are running the most recent version of dbatools

2.0.4

### Other details or mentions

I pulled the code and was able to find the issue & fix.  I also found another potential issue that I'll include here.  Line numbers are based on the line numbers in the code as seen at https://github.com/dataplat/dbatools/blob/master/public/New-DbaDbUser.ps1\

For this particular bug, the issue is on line 172.  Concerning the -Database input parameter, the docs say "...If unspecified, all user databases will be processed."  Line 172 attempts to use the value of the -Database parameter to control all code adding users.  If that parameter is not provided, there are no values to iterate through, and the function will exit immediately without doing any further work.  The solution is to force this foreach loop to iterate over the internal $databases parameter created on line 169.  

Either of the following two code blocks appears to resolve the issue.  I prefer the second; YMMV
Lines 172-173:
``` 
foreach ($db in $databases.Name) { #We should be looking at $databases (internal) instead of $Databases (input). We need to reference the name property because this is now a collection of database objects
                $dbSmo = $databases | Where-Object Name -eq $db
```
Lines  172-173:
```
foreach ($dbSmo in $databases) { #We should be looking at $databases (internal) instead of $Databases (input). We need to reference the name property because this is now a collection of database objects
                #$dbSmo = $databases | Where-Object Name -eq $db #Commented out because $dbSmo is now assigned in the foreach statement
```
The output statements via stop-function and write-verbose inside the loop appear to use $dbSmo and $db interchangeably, but the content of those variables seems to be different.  I'm looking into normalizing that now.

The second, unexpected, potential bug is on line 157:
``` } elseif (-not $IncludeSystem) { ```
This makes evaluation of -IncludeSystem dependent on the existence (or lack thereof) of -Databases.  If I'm not mistaken, -IncludeSystem is independent of -Databases, similar to -ExcludeDatabases (which has its own if statement on line 160).  If so, then the elseif on 157 should be converted to a standalone if statement.

I have run these fixes through a few tests locally; behavior thus far is as expected. 

### What PowerShell host was used when producing this error

Windows PowerShell (powershell.exe)

### PowerShell Host Version

Name                           Value                                                               
----                           -----                                                               
PSVersion                      5.1.22621.1778                                                      
PSEdition                      Desktop                                                             
PSCompatibleVersions           {1.0, 2.0, 3.0, 4.0...}                                             
BuildVersion                   10.0.22621.1778                                                     
CLRVersion                     4.0.30319.42000                                                     
WSManStackVersion              3.0                                                                 
PSRemotingProtocolVersion      2.3                                                                 
SerializationVersion           1.1.0.1                                                             

### SQL Server Edition and Build number

N/A

### .NET Framework Version

.NET Framework 4.8.9167.0

### PR DESCRIPTION
**Pull request by sqlarticles**
## Please read -- recent changes to our repo
On November 10, 2022, [we removed some bloat from our repository (for the second and final time)](https://github.com/dataplat/dbatools/issues/8542). This change requires that all contributors reclone or refork their repo.

PRs from repos that have not been recently reforked or recloned will be closed and @potatoqualitee will cherry-pick your commits and open a new PR with your changes.

 - [x ] Please confirm you have the smaller repo (85MB .git directory vs 275MB or 110MB or 185MB .git directory)

## Type of Change

 - [x ] Bug fix (non-breaking change, fixes # )
 - [ ] New feature (non-breaking change, adds functionality, fixes # )
 - [ ] Breaking change (affects multiple commands or functionality, fixes # )
 - [ ] Ran manual Pester test and has passed (`.\tests\manual.pester.ps1`)
 - [ ] Adding code coverage to existing functionality
 - [x ] Pester test is included
 - [ ] If new file reference added for test, has is been added to github.com/dataplat/appveyor-lab ?
 - [ ] Unit test is included
 - [ ] Documentation
 - [ ] Build system

### Approach

Bug fix #9068 

`New-DbaDbUser` function failed to create the user in all the user databases when `Database` parameter is not provided. Changes are made to fix this, when the `Database` parameter is not provided then the user will be created in all the user databases.

### Commands to test

`New-DbaDbUser -SqlInstance Server1 -Login User1`

### CODE REVIEW

**Comment by wsmelton** [comment]
Test is failing for adding users to multiple databases:

image

**Comment by sqlarticles** [comment]
Thanks, @wsmelton. My office network blocks downloading anything from GitHub.  Couldn't check this when I'm in office.

I added a new test to cover this scenario. Looks like the test server has more database than the ones created for this testing. I will modify the test so that it matches with the total number of user databases in the test server.

**Comment by sqlarticles** [comment]
@wsmelton Fixed the tests, its looking good now. Can you please review?

**Comment by sqlarticles** [comment]
Can this PR get reviewed please?

**Comment by potatoqualitee** [comment]
yes, our apologies, @sqlarticles. We had code signing issues that preventing merging/releasing. Tests pass, your code looks good and we very much appreciate the PR 👍🏼 💯

**Pull request merged**
