### PR TITLE
Invoke-DbaQuery - default to nonpooled connection

### LINKED ISSUE #8491: Request for comment: Defaulting Invoke-DbaQuery to Non-pooled connection
### Summarize Command's Functionality

Considering the solution for [Can't drop temp stored procs](https://github.com/dataplat/dbatools/issues/8472) and the fact that `Invoke-Sqlcmd` uses non-pooled by default, I'd like to propose that Invoke-DbaQuery does too.

The alternative is that we parse the SQL for temp objects and force it to Non-pooled the way we detect and force it for Credentialed (not integrated) Windows Auth.

In order to perfectly detect a temp object, we'd have to add 14MB of DLLs.

```
$parseoptions = New-Object Microsoft.SqlServer.Management.SqlParser.Parser.ParseOptions
$parseoptions .BatchSeparator = $BatchSeparator

$sql = "CREATE PROC #DropStatistics
AS
SELECT 1
GO
drop procedure #DropStatistics
go"

$parser = [Microsoft.SqlServer.Management.SqlParser.Parser.Parser]::Parse($sql, $parseoptions )
$parser.Script.Tokens | Where-Object { $PSItem.Text.StartsWith('#') }
```

We can also use the parser within our own parsing (which is currently regex, I believe).

The downside to parsing is that it will slow down the import of dbatools by 130ms and increase the size by 14MB uncompressed.

### Is there a command that is similiar or close to what you are looking for?

Yes

### Technical Details

_No response_

### PR DESCRIPTION
**Pull request by potatoqualitee**
Fixes #8491, #8472

### CODE REVIEW

**Comment by andreasjordan** [comment]
Will have a look later today...

**Comment by potatoqualitee** [comment]
Thank you! I had one timeout with pwsh on Windows GH Actions test and had to re-run it. It ran with success but I'd like to keep an eye on this and perhaps hold this patch in Dev for a couple days before releasing.

**Comment by andreasjordan** [comment]
That is my idea of bypassing Connect-DbaInstance if possible as a performance boost.

image

But I can revert, if this is more than you would like to do in this PR.

**Comment by andreasjordan** [comment]
Thanks for fixing the formatting.

**Comment by potatoqualitee** [comment]
I think this is great! I'll merge and we can use it for a few days before pushing it out 🔥

**Comment by potatoqualitee** [comment]
that's a HUGE boost too! 🚤

**Pull request merged**
